import type { ModuleDefinition } from "../types";
import { adminRoute, api, deprecated, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const contentModules: ModuleDefinition[] = [
{
    id: "announcements",
    label: "Announcements",
    description: "Employee-visible announcements from LINE group messages (via announcement-groups binding), locally managed system announcements, and resource portal announcements.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 2, supervisor: 4 },
    routes: [
      portalRoute("/portal/:facilityKey/announcements"),
      portalRoute("/portal/:facilityKey/announcements/:id"),
      roleRoute("employee", "/employee/announcements"),
      roleRoute("supervisor", "/supervisor/announcements"),
    ],
    apis: [
      api("GET", "/api/facility-home/:groupId/announcements", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements/:id", "proxy", legacy),
      api("POST", "/api/facility-home/:groupId/announcements/:id/ack", "proxy", legacy),
      api("GET", "/api/announcements/acknowledgements", "crud", partial),
      api("POST", "/api/announcements/:id/ack", "crud", partial),
      api("GET", "/api/portal/system-announcements", "crud", partial),
      api("POST", "/api/portal/system-announcements", "crud", partial),
      api("PATCH", "/api/portal/system-announcements/:id", "crud", partial),
      api("DELETE", "/api/portal/system-announcements/:id", "crud", partial),
    ],
    data: [
      { table: "system_announcements", entity: "system announcement", source: "postgres", status: implemented },
      { table: "announcement_acknowledgements", entity: "employee announcement acknowledgement", source: "postgres", status: partial },
      { table: "portal_events", entity: "announcement read/open events", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Facility announcements and acknowledgement proxy.", status: external }],
    bff: {
      employeeSectionKey: "announcements",
      supervisorSectionKey: "announcementAcks",
      plannedEndpoints: ["/api/bff/employee/home"],
      uiStates: ["loading", "ready", "empty", "error", "degraded", "stale", "disabled"],
      freshness: "5min",
      uiStateSourceFiles: ["client/src/modules/employee/home/employee-home-page.tsx", "client/src/modules/supervisor/announcements/page.tsx"],
      sharedComponents: ["AnnouncementCard", "FreshnessIndicator"],
    },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["announcement_open", "pageview"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], requiresApproval: false, notes: "Employee-visible content may come from LINE proxy or local system_announcements." },
    legacy: { oldRoutes: ["/portal/:facilityKey/announcements", "/api/facility-home/:groupId/announcements"] },
  },
{
    id: "announcement-groups",
    label: "Announcement Groups",
    description: "Facility to LINE group binding management for employee group announcements.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: { supervisor: 9 },
    routes: [
      roleRoute("supervisor", "/supervisor/announcement-groups"),
      adminRoute("/admin/announcement-groups", legacy),
    ],
    apis: [
      api("GET", "/api/integrations/announcement-groups/messages", "bff"),
      api("GET", "/api/admin/announcement-groups", "crud"),
      api("POST", "/api/admin/announcement-groups", "crud"),
      api("PATCH", "/api/admin/announcement-groups/:id", "crud"),
      api("DELETE", "/api/admin/announcement-groups/:id", "crud"),
      api("POST", "/api/admin/announcement-groups/:id/test-fetch", "crud"),
    ],
    data: [{ table: "facility_announcement_groups", entity: "facility LINE announcement group binding", source: "postgres", status: implemented }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Read LINE group text messages by facility binding.", status: external }],
    bff: { employeeSectionKey: "announcements", supervisorSectionKey: "announcementGroups", plannedEndpoints: ["/api/bff/employee/home", "/api/integrations/announcement-groups/messages"] },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["announcement_group_create", "announcement_group_update", "announcement_group_delete", "announcement_group_test_fetch"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], requiresApproval: false, notes: "Employees may preview resolved group announcements but cannot mutate group bindings." },
    legacy: { oldRoutes: ["/admin/announcement-groups"] },
  },
{
    id: "announcement-review",
    label: "Announcement Review",
    description: "Supervisor review queue for LINE Bot announcement candidates.",
    domainType: "support",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/announcements"), portalRoute("/portal/:facilityKey/review", partial), roleRoute("supervisor", "/supervisor/announcements")],
    apis: [
      api("GET", "/api/announcement-candidates", "proxy", legacy),
      api("GET", "/api/announcement-candidates/:id", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy),
    ],
    data: [{ table: "audit_logs", entity: "review audit trail", source: "postgres", status: planned, notes: "Server-side audit write path is still planned." }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Candidate approval/rejection upstream.", status: external }],
    bff: { supervisorSectionKey: "announcementReview", plannedEndpoints: ["/api/announcement-candidates"] },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["announcement_approve", "announcement_reject"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], requiresApproval: true, notes: "Review actions must eventually write audit logs." },
    legacy: { oldRoutes: ["/announcements", "/portal/:facilityKey/review"] },
  },
{
    id: "announcement-summary",
    label: "Announcement Summary",
    description: "Announcement dashboard summary and weekly report export view.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/announcements/summary")],
    apis: [
      api("GET", "/api/announcement-dashboard/summary", "proxy", legacy),
      api("GET", "/api/announcement-reports/weekly", "proxy", legacy),
    ],
    data: [{ table: "source_snapshots", entity: "announcement summary snapshot", source: "external", status: partial }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Summary and weekly report upstream.", status: external }],
    bff: { supervisorSectionKey: "announcementSummary", plannedEndpoints: ["/api/announcement-dashboard/summary"] },
    telemetry: { trackPageView: true },
    governance: { ownerRole: "supervisor", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Summary reads upstream report data; local persistence is not complete." },
    legacy: { oldRoutes: ["/announcements/summary"] },
  },
{
    id: "system-announcements",
    label: "System Announcements",
    description: "Supervisor-maintained operational notices stored locally for portal and employee home display.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 3, supervisor: 5 },
    routes: [portalRoute("/portal/:facilityKey/manage", partial), roleRoute("supervisor", "/supervisor/announcements")],
    apis: [
      api("GET", "/api/portal/system-announcements", "crud"),
      api("POST", "/api/portal/system-announcements", "crud"),
      api("PATCH", "/api/portal/system-announcements/:id", "crud"),
      api("DELETE", "/api/portal/system-announcements/:id", "crud"),
    ],
    data: [{ table: "system_announcements", entity: "system announcement", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Local supervisor-managed notices.", status: implemented }],
    bff: { employeeSectionKey: "announcements", supervisorSectionKey: "announcements" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Local system announcements are editable by supervisors for their facility scope." },
  },
{
    id: "handover",
    label: "交辦事項",
    description: "Facility-scoped shared assignment surface for counter, lifeguard, and supervisor roles.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 4, supervisor: 3 },
    routes: [portalRoute("/portal/:facilityKey/handover"), roleRoute("employee", "/employee/handover"), roleRoute("lifeguard", "/lifeguard/handover"), roleRoute("supervisor", "/supervisor/handover")],
    apis: [
      api("GET", "/api/portal/handovers", "crud"),
      api("POST", "/api/portal/handovers", "crud"),
      api("DELETE", "/api/portal/handovers/:id", "crud"),
      api("POST", "/api/handover", "crud"),
      api("POST", "/api/handover/image-upload", "upload"),
      api("PATCH", "/api/handover/:id/read", "crud"),
      api("PATCH", "/api/handover/:id/reply", "crud"),
      api("PATCH", "/api/handover/:id/complete", "crud"),
      api("GET", "/api/bff/employee/handover/summary", "bff"),
      api("GET", "/api/bff/employee/handover/list", "bff"),
      api("GET", "/api/portal/operational-handovers", "crud"),
      api("POST", "/api/portal/operational-handovers", "crud"),
      api("PATCH", "/api/portal/operational-handovers/:id", "crud"),
      api("PATCH", "/api/portal/operational-handovers/:id/report", "crud"),
      api("DELETE", "/api/portal/operational-handovers/:id", "crud"),
      api("GET", "/api/facility-home/:groupId/handover", "proxy", legacy),
    ],
    data: [
      { table: "handover_entries", entity: "legacy handover entry", source: "postgres", status: implemented },
      { table: "operational_handovers", entity: "operational handover", source: "postgres", status: implemented },
      { table: "portal_events", entity: "handover events", source: "telemetry", status: implemented },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Local handover persistence.", status: implemented },
      { provider: "OBJECT_STORAGE", purpose: "Handover image record uploads.", status: implemented },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Optional assignee resolution from schedule export.", status: partial },
    ],
    bff: {
      employeeSectionKey: "handover",
      supervisorSectionKey: "handoverOverview",
      plannedEndpoints: ["/api/bff/employee/handover/list", "/api/bff/employee/handover/summary", "/api/bff/supervisor/dashboard"],
      uiStates: ["loading", "ready", "empty", "error", "disabled"],
      freshness: "realtime",
      uiStateSourceFiles: ["client/src/modules/employee/handover/page.tsx", "client/src/modules/supervisor/handover/page.tsx", "client/src/modules/supervisor/dashboard-page.tsx"],
      sharedComponents: ["DenseRow", "StatCard"],
    },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["handover_create", "handover_report", "handover_claim", "handover_complete", "handover_reply", "handover_delete"] },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "lifeguard", "supervisor"], readonlyFor: [], notes: "交辦事項是舊任務與舊個人記事退役後唯一工作事項頁；counter/employee, lifeguard, and supervisor share operational_handovers by facilityKey." },
    legacy: { oldRoutes: ["/portal/:facilityKey/handover", "/api/facility-home/:groupId/handover"] },
  },
{
    id: "anomalies",
    label: "Anomalies",
    description: "Clock-in anomaly reports, review, resolution, and system alert surfaces.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { system: 3 },
    routes: [adminRoute("/anomaly-reports"), roleRoute("system", "/system/alerts")],
    apis: [
      api("POST", "/api/anomaly-report", "upload"),
      api("GET", "/api/anomaly-reports", "crud"),
      api("GET", "/api/anomaly-reports/:id", "crud"),
      api("PATCH", "/api/anomaly-reports/:id/resolution", "crud"),
      api("PATCH", "/api/anomaly-reports/batch/resolution", "crud"),
      api("DELETE", "/api/anomaly-reports/:id", "crud"),
    ],
    data: [
      { table: "anomaly_reports", entity: "anomaly report", source: "postgres", status: implemented },
      { table: "audit_logs", entity: "anomaly resolution audit", source: "postgres", status: planned, notes: "Resolution audit write path is still planned." },
    ],
    integrations: [
      { provider: "GMAIL_SMTP", purpose: "Notification email for new reports/resolution.", status: partial },
      { provider: "OBJECT_STORAGE", purpose: "Current upload path is local uploads; object storage is future replacement.", status: planned },
    ],
    bff: { supervisorSectionKey: "pendingAnomalies", systemSectionKey: "alerts" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], requiresApproval: true, notes: "Anomaly resolution should fail closed into audit before production hardening." },
  },
{
    id: "notification-recipients",
    label: "Notification Recipients",
    description: "Email recipient management for anomaly notification flows.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["system", "supervisor"],
    visibility: ["admin_page", "background_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/anomaly-reports", partial)],
    apis: [
      api("GET", "/api/notification-recipients", "crud"),
      api("POST", "/api/notification-recipients", "crud"),
      api("PATCH", "/api/notification-recipients/:id", "crud"),
      api("DELETE", "/api/notification-recipients/:id", "crud"),
    ],
    data: [{ table: "notification_recipients", entity: "notification recipient", source: "postgres", status: implemented }],
    integrations: [{ provider: "GMAIL_SMTP", purpose: "Recipient list controls Gmail notification delivery.", status: partial }],
    bff: { systemSectionKey: "notificationRecipients", plannedEndpoints: ["/api/notification-recipients"] },
    telemetry: { trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system", "supervisor"], readonlyFor: [], requiresApproval: false, notes: "Recipient edits affect external email delivery and should be audited later." },
  },
{
    id: "campaigns-events",
    label: "Campaigns and Events",
    description: "Employee-visible events/campaigns from employee resources and announcement candidate fallback.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 6 },
    routes: [portalRoute("/portal/:facilityKey/campaigns"), roleRoute("employee", "/employee/announcements", partial)],
    apis: [api("GET", "/api/portal/employee-resources", "crud", partial), api("POST", "/api/portal/employee-resources", "crud", partial)],
    data: [{ table: "employee_resources", entity: "event resource", source: "postgres", status: implemented, notes: "category=event" }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Campaign fallback extracted from announcement candidates.", status: external }],
    bff: { employeeSectionKey: "campaigns" },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["resource_create"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Employee-created campaign/event content is allowed but scoped by facility." },
    legacy: { oldRoutes: ["/portal/:facilityKey/campaigns"] },
  },
{
    id: "booking-snapshot",
    label: "Booking Snapshot",
    description: "Booking and occupancy snapshot module reserved for future booking adapter projection.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "background_only"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 10, supervisor: 10, system: 10 },
    routes: [],
    apis: [api("GET", "/api/bff/system/module-health/booking-snapshot", "bff", partial)],
    data: [{ table: "booking_snapshots", entity: "booking occupancy snapshot", source: "postgres", status: partial, notes: "Stub table built; booking adapter projection not yet connected." }],
    integrations: [{ provider: "UNKNOWN", purpose: "Booking adapter exists as a boundary but real provider is not connected.", status: planned }],
    bff: { employeeSectionKey: "bookingSnapshot", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Planned only; connect through booking adapter before exposing as real data." },
  },
{
    id: "shift-reminder",
    label: "Shift Reminder",
    description: "Today shift and reminder section from Smart Schedule Manager and facility-home proxy.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 7, supervisor: 7 },
    routes: [portalRoute("/portal/:facilityKey/shift"), roleRoute("employee", "/employee/shift")],
    apis: [
      api("GET", "/api/facility-home/:groupId/today-shift", "proxy", legacy),
      api("GET", "/api/bff/employee/shifts/today", "bff", partial),
      api("GET", "/api/bff/system/schedule-snapshot", "bff", partial),
    ],
    data: [{ table: "source_snapshots", entity: "schedule source snapshot", source: "external", status: partial }],
    integrations: [
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Canonical shift export and schedule snapshot.", status: external },
      { provider: "LINE_BOT_ASSISTANT", purpose: "Legacy facility-home today-shift proxy.", status: legacy },
    ],
    bff: { employeeSectionKey: "shifts", supervisorSectionKey: "shifts", systemSectionKey: "scheduleSnapshot", plannedEndpoints: ["/api/bff/system/schedule-snapshot"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Schedule data should enter through adapter/projection, not direct frontend calls." },
    legacy: { oldRoutes: ["/portal/:facilityKey/shift", "/api/facility-home/:groupId/today-shift"] },
  },
{
    id: "quick-links",
    label: "Quick Links",
    description: "Supervisor-managed shortcuts used by portal and employee home.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 8, supervisor: 8 },
    routes: [portalRoute("/portal/:facilityKey/manage"), roleRoute("employee", "/employee/more", partial)],
    apis: [
      api("GET", "/api/portal/quick-links", "crud"),
      api("POST", "/api/portal/quick-links", "crud"),
      api("PATCH", "/api/portal/quick-links/:id", "crud"),
      api("DELETE", "/api/portal/quick-links/:id", "crud"),
    ],
    data: [{ table: "quick_links", entity: "quick link", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Local shortcut persistence.", status: implemented }],
    bff: { employeeSectionKey: "shortcuts" },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["link_click"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Supervisor manages facility-scoped quick links." },
    legacy: { oldRoutes: ["/portal/:facilityKey/manage"] },
  },
{
    id: "notification-center",
    label: "Notification Center",
    description: "Unified in-app notifications planned after core domain events are stable.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "background_only"],
    sourceOfTruth: "none",
    homepageWidget: true,
    priority: { employee: 11, supervisor: 11, system: 11 },
    routes: [],
    apis: [api("GET", "/api/bff/system/module-health/notification-center", "bff", partial)],
    data: [{ table: "notification_hub", entity: "notification hub event", source: "postgres", status: partial, notes: "Stub table built; event ingestion pipeline not yet connected." }],
    integrations: [{ provider: "UNKNOWN", purpose: "Will consume domain events after telemetry/audit contract is stable.", status: planned }],
    bff: { employeeSectionKey: "notifications", supervisorSectionKey: "notifications", systemSectionKey: "notifications" },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Planned module; requires event policy before implementation." },
  },
{
    id: "knowledge-base-qna",
    label: "相關問題詢問",
    description: "Employee Q&A knowledge base for self-service questions, answers, tags, and homepage fuzzy search.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 12 },
    routes: [
      { role: "employee", path: "/employee/qna", kind: "employee", status: partial },
      roleRoute("supervisor", "/supervisor/qna-review", partial),
      { path: "/api/portal/knowledge-base-qna", kind: "api", status: partial },
    ],
    apis: [
      { method: "GET", path: "/api/portal/knowledge-base-qna", kind: "crud", status: partial },
      { method: "POST", path: "/api/portal/knowledge-base-qna", kind: "crud", status: partial },
      { method: "POST", path: "/api/portal/knowledge-base-qna/media", kind: "upload", status: partial },
      { method: "PATCH", path: "/api/portal/knowledge-base-qna/:id", kind: "crud", status: partial },
      { method: "DELETE", path: "/api/portal/knowledge-base-qna/:id", kind: "crud", status: partial },
      { method: "GET", path: "/api/bff/employee/search", kind: "bff", status: partial },
    ],
    data: [{ table: "knowledge_base_qna", entity: "employee Q&A", source: "postgres", status: partial, notes: "Facility-scoped Q&A entries searchable by question, answer, category, and tags." }],
    integrations: [{ provider: "POSTGRES", purpose: "Stores employee Q&A knowledge base entries.", status: partial }],
    bff: { employeeSectionKey: "qna" },
    telemetry: { trackPageView: true, trackActionSubmit: true, eventTypes: ["SEARCH_SUBMIT", "KNOWLEDGE_QNA_CREATED", "KNOWLEDGE_QNA_UPDATED", "KNOWLEDGE_QNA_DELETED"] },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "supervisor", "system"], readonlyFor: [], notes: "Employees can create and answer their own Q&A; supervisor/system governance can curate later." },
  },
{
    id: "activity-periods",
    label: "活動檔期 / 課程快訊",
    description: "Employee activity-period and course-news surface backed by employee_resources and announcement/event content.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 3 },
    routes: [roleRoute("employee", "/employee/activity-periods", partial), roleRoute("employee", "/employee/activity-periods/:id", partial), portalRoute("/portal/:facilityKey/campaigns", partial)],
    apis: [
      api("GET", "/api/portal/employee-resources", "crud", partial),
      api("GET", "/api/facility-home/:groupId/campaigns", "proxy", legacy),
    ],
    data: [{ table: "employee_resources", entity: "activity and course resource", source: "postgres", status: implemented, notes: "category=event or announcement-like course content." }],
    integrations: [{ provider: "POSTGRES", purpose: "Employee activity period and course-news content.", status: implemented }],
    bff: { employeeSectionKey: "events" },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "supervisor", "system"], readonlyFor: [], notes: "Employee can view and use entry points; supervisor remains content governance owner." },
  },
{
    id: "registration-courses",
    label: "報名 / 課程",
    description: "Registration and course entry placeholder; booking provider is not connected yet.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 23 },
    routes: [roleRoute("employee", "/employee/registration-courses", partial)],
    apis: [api("GET", "/api/bff/system/module-health/registration-courses", "bff", partial)],
    data: [{ table: "registration_courses", entity: "registration course stub", source: "postgres", status: partial }],
    integrations: [{ provider: "UNKNOWN", purpose: "Future course registration provider.", status: planned }],
    bff: { employeeSectionKey: "registrationCourses" },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee"], notes: "Not connected; renders not-connected surface through EmployeeMorePage." },
  },
{
    id: "employee-settings",
    label: "員工設定",
    description: "Employee-facing settings surface for shortcut ordering and workbench preferences.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee"],
    visibility: ["detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("employee", "/employee/settings", partial)],
    apis: [api("GET", "/api/portal/quick-links", "crud", partial), api("PATCH", "/api/portal/layout-settings", "legacy", deprecated)],
    data: [
      { table: "quick_links", entity: "shortcut entries", source: "postgres", status: implemented },
      { table: "widget_layout_settings", entity: "legacy widget ordering", source: "legacy", status: deprecated },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Employee preferences and shortcut ordering.", status: partial }],
    bff: { employeeSectionKey: "settings" },
    telemetry: { trackPageView: true, trackActionSubmit: true, eventTypes: ["layout_update"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "system"], readonlyFor: ["supervisor"], notes: "Settings is a route-level support surface, not a sidebar module." },
  },
{
    id: "search",
    label: "快速搜尋",
    description: "Global workbench search over registered modules, announcements, handovers, shifts, entry points, and common questions.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "background_only"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { employee: 30, lifeguard: 30, supervisor: 30, system: 30 },
    routes: [roleRoute("supervisor", "/supervisor/facilities", partial), roleRoute("supervisor", "/supervisor/facilities/:facilityKey", partial), roleRoute("supervisor", "/supervisor/people", partial)],
    apis: [api("GET", "/api/search/global", "bff", partial)],
    data: [{ table: "MODULE_REGISTRY", entity: "search index seed", source: "private", status: partial }],
    integrations: [{ provider: "POSTGRES", purpose: "Searchable workbench content once full-text projection is wired.", status: partial }],
    bff: { employeeSectionKey: "search", supervisorSectionKey: "search", systemSectionKey: "search" },
    telemetry: { trackActionSubmit: true, eventTypes: ["SEARCH_SUBMIT"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "lifeguard", "supervisor"], notes: "Search is a shared background capability, not a dedicated route." },
  },
{
    id: "weather-widget",
    label: "天氣卡片",
    description: "Employee home weather widget powered by CWA (中央氣象局) open data API, station 466920 (板橋). 10-minute in-memory cache.",
    domainType: "integration",
    status: implemented,
    visibleRoles: ["employee"],
    visibility: ["homepage_widget"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 60 },
    routes: [],
    apis: [api("GET", "https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0003-001", "proxy")],
    data: [],
    integrations: [{ provider: "CWA", purpose: "Real-time temperature, humidity and weather condition from 板橋 station (466920). Requires CWA_API_KEY env var.", status: implemented }],
    bff: { employeeSectionKey: "weather" },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee"], notes: "CWA_API_KEY must be set. Gracefully degrades to unavailable when key is missing or API times out." },
  },
{
    id: "group-broadcasts",
    label: "群組重要公告",
    description: "Supervisor-posted group broadcasts with 三蘆區 fan-out and Gemini 2.0 Flash event detection. Auto-inserts detected events into announcement_candidates.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 3, supervisor: 5 },
    routes: [
      roleRoute("supervisor", "/supervisor/group-broadcasts"),
    ],
    apis: [
      api("GET", "/api/group-broadcasts", "bff"),
      api("POST", "/api/group-broadcasts", "crud"),
      api("GET", "/api/group-broadcasts/admin", "crud"),
      api("DELETE", "/api/group-broadcasts/:id", "crud"),
    ],
    data: [
      { table: "group_broadcasts", entity: "group broadcast record", source: "postgres", status: implemented },
    ],
    integrations: [{ provider: "UNKNOWN", purpose: "Gemini 2.0 Flash: detect events in broadcast content; auto-insert into announcement_candidates.", status: partial }],
    bff: { employeeSectionKey: "announcements", supervisorSectionKey: "groupBroadcasts" },
    telemetry: { trackPageView: true, trackActionSubmit: true, eventTypes: ["group_broadcast_create", "group_broadcast_delete"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee", "lifeguard"], requiresApproval: false, notes: "三蘆區 fan-out automatically distributes to xinbei_pool, salu_counter, sanmin_pool. GOOGLE_API_KEY required for Gemini; gracefully skips if absent." },
  },
];
