import type { ModuleDefinition } from "../types";
import { adminRoute, api, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const foundationModules: ModuleDefinition[] = [
{
    id: "auth",
    label: "Authentication and Session",
    description: "Workbench login, role/facility switching, legacy Ragic portal login, and session governance.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/login", partial), roleRoute("system", "/login", partial)],
    apis: [
      api("POST", "/api/auth/login", "auth"),
      api("POST", "/api/auth/logout", "auth"),
      api("GET", "/api/auth/me", "auth"),
      api("GET", "/api/auth/facility-candidates", "auth", partial),
      api("POST", "/api/auth/active-facility", "auth"),
      api("POST", "/api/auth/active-role", "auth"),
      api("POST", "/api/auth/ragic-login", "auth", legacy),
    ],
    data: [
      { table: "users", entity: "legacy user credential", source: "postgres", status: legacy, notes: "Original user table still exists for compatibility." },
      { table: "sessions_index", entity: "session index", source: "postgres", status: partial, notes: "Session index schema exists; cookie/session hardening is still in progress." },
      { table: "auth_audit_logs", entity: "auth audit log", source: "postgres", status: partial },
    ],
    integrations: [
      { provider: "RAGIC", purpose: "Employee auth and H05 OT facility candidate lookup.", status: external },
      { provider: "LOCAL_STORAGE", purpose: "Former portal auth hint; not a source of truth.", status: legacy, notes: "Do not use localStorage as authority." },
      { provider: "POSTGRES", purpose: "Session, user, and audit tables.", status: partial },
    ],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true, eventTypes: ["login", "logout", "role_switch", "facility_switch"] },
    governance: {
      ownerRole: "SYSTEM_ADMIN",
      editableBy: ["SYSTEM_ADMIN"],
      readonlyFor: ["system"],
      requiresApproval: true,
      notes: "Authentication policy is system-governed; legacy Ragic login remains registered until migration is complete.",
    },
    legacy: { oldRoutes: ["/portal/login", "/api/auth/ragic-login"], migrationNotes: "Keep legacy portal route while workbench session becomes the single authority." },
  },
{
    id: "dashboard",
    label: "Dashboard",
    description: "Legacy admin dashboard plus supervisor/system/employee workbench home shell orchestration.",
    domainType: "derived",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { employee: 1, supervisor: 1, system: 1 },
    routes: [
      adminRoute("/"),
      roleRoute("employee", "/employee"),
      roleRoute("employee", "/employee/home"),
      roleRoute("supervisor", "/supervisor"),
      roleRoute("supervisor", "/supervisor/home"),
      roleRoute("system", "/system"),
      roleRoute("system", "/system/overview"),
    ],
    apis: [
      api("GET", "/api/bff/employee/home", "bff", partial),
      api("GET", "/api/bff/supervisor/dashboard", "bff", partial),
      api("GET", "/api/bff/system/overview", "bff", partial),
      api("GET", "/api/admin/overview", "proxy", legacy),
    ],
    data: [
      { table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial },
      { table: "supervisor_dashboard_projection", entity: "supervisor dashboard projection", source: "projection", status: partial },
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
    ],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "Announcement and employee home fallback summaries.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Supervisor staffing and shift summaries.", status: external },
      { provider: "POSTGRES", purpose: "Projection cache and local portal data.", status: partial },
    ],
    bff: { employeeSectionKey: "home", supervisorSectionKey: "dashboard", systemSectionKey: "overview", plannedEndpoints: ["/api/bff/employee/home", "/api/bff/supervisor/dashboard", "/api/bff/system/overview"] },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["CARD_CLICK"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Dashboard composition should stay in BFF DTOs, not page-local fetch fan-out." },
    legacy: { oldRoutes: ["/", "/api/admin/overview"], migrationNotes: "Legacy admin dashboard remains available while workbench routes are primary." },
  },
{
    id: "employee-home",
    label: "員工首頁",
    description: "Employee workbench home composition from active facility, BFF home cards, and fixed dashboard slots.",
    domainType: "derived",
    status: implemented,
    visibleRoles: ["employee"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { employee: 1 },
    routes: [roleRoute("employee", "/employee"), roleRoute("employee", "/employee/home")],
    apis: [api("GET", "/api/bff/employee/home", "bff")],
    data: [
      { table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial },
      { table: "operational_handovers", entity: "handover summary", source: "postgres", status: implemented },
      { table: "employee_resources", entity: "events, documents, notes, and local announcements", source: "postgres", status: implemented },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Facility-scoped employee dashboard content.", status: implemented }],
    bff: { employeeSectionKey: "home", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["CARD_CLICK"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor", "system"], readonlyFor: [], notes: "Home layout is fixed by current product decision; widget data stays BFF-owned." },
  },
{
    id: "lifeguard-home",
    label: "救生首頁",
    description: "Lifeguard operation home with six mobile-first module cards and daily record summary.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { lifeguard: 1 },
    routes: [roleRoute("lifeguard", "/lifeguard"), roleRoute("lifeguard", "/lifeguard/home")],
    apis: [api("GET", "/api/bff/lifeguard/home", "bff", partial)],
    data: [
      { table: "lifeguard_*", entity: "lifeguard daily operation summaries", source: "postgres", status: partial },
      { table: "daily_report_submissions", entity: "lifeguard work-log summary", source: "postgres", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Lifeguard home projection and operation counts.", status: partial }],
    bff: { employeeSectionKey: "lifeguardHome", plannedEndpoints: ["/api/bff/lifeguard/home"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "Desktop structure and mobile operation entry share the same module config." },
  },
{
    id: "lifeguard-log",
    label: "救生員日誌",
    description: "Lifeguard daily log, water quality form, handover notes, task completions, report submission, and review bridge.",
    domainType: "core",
    status: partial,
    visibleRoles: ["lifeguard", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 8 },
    routes: [roleRoute("lifeguard", "/lifeguard/log"), portalRoute("/portal/:facilityKey/work-log", partial)],
    apis: [
      api("GET", "/api/bff/lifeguard/home", "bff", partial),
      api("GET", "/api/work-logs/today", "crud", partial),
      api("POST", "/api/work-logs/handover", "crud", partial),
    ],
    data: [
      { table: "work_log_task_completions", entity: "lifeguard task completion", source: "postgres", status: implemented },
      { table: "water_quality_records", entity: "water quality record", source: "postgres", status: implemented },
      { table: "lifeguard_handover_notes", entity: "lifeguard handover note", source: "postgres", status: implemented },
      { table: "daily_report_submissions", entity: "daily report submission", source: "postgres", status: implemented },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Lifeguard work-log records and review trail.", status: implemented }],
    bff: { employeeSectionKey: "lifeguardLog", supervisorSectionKey: "lifeguardLog" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["LIFEGUARD_LOG_CREATED", "LIFEGUARD_LOG_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "Detailed lifeguard log remains the bridge while operation modules are completed." },
  },
{
    id: "supervisor-dashboard",
    label: "主管儀表板",
    description: "Supervisor workbench dashboard for operations overview, facility cards, module preview drawers, and review counts.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { supervisor: 1 },
    routes: [roleRoute("supervisor", "/supervisor"), roleRoute("supervisor", "/supervisor/home")],
    apis: [api("GET", "/api/bff/supervisor/dashboard", "bff", partial)],
    data: [{ table: "supervisor_dashboard_projection", entity: "supervisor dashboard projection", source: "projection", status: partial }],
    integrations: [{ provider: "POSTGRES", purpose: "Supervisor dashboard projection and module previews.", status: partial }],
    bff: { supervisorSectionKey: "dashboard", plannedEndpoints: ["/api/bff/supervisor/dashboard"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], notes: "Supervisor dashboard is the official shell entry; legacy admin dashboard redirects away." },
  },
{
    id: "system-dashboard",
    label: "系統總覽",
    description: "Legacy system overview entry retained behind the new five-entry control center.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["detail_page", "system_only"],
    sourceOfTruth: "projection",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system"), roleRoute("system", "/system/overview")],
    apis: [api("GET", "/api/bff/system/overview", "bff", partial)],
    data: [{ table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial }],
    integrations: [{ provider: "POSTGRES", purpose: "System overview projection and module health summary.", status: partial }],
    bff: { systemSectionKey: "overview", plannedEndpoints: ["/api/bff/system/overview"] },
    telemetry: { trackPageView: true, eventTypes: ["MODULE_HEALTH_VIEW"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: [], notes: "Replaced in navigation by system-control-center; retained for compatibility only." },
    legacy: { oldRoutes: ["/system/overview"], migrationNotes: "Primary IT entry is /system via system-control-center." },
  },
{
    id: "system-control-center",
    label: "系統控制中心",
    description: "IT control center that aggregates module health, watchdog alerts, audit volume, and governance status into five entry tiles.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { system: 1 },
    routes: [roleRoute("system", "/system")],
    apis: [api("GET", "/api/bff/system/control-center", "bff")],
    data: [
      { table: "watchdog_events", entity: "recent watchdog events", source: "telemetry", status: implemented },
      { table: "audit_logs", entity: "24h audit volume", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Aggregates registry, audit, and watchdog telemetry.", status: partial }],
    bff: { systemSectionKey: "controlCenter", plannedEndpoints: ["/api/bff/system/control-center"] },
    telemetry: { trackPageView: true, eventTypes: ["SYSTEM_CONTROL_CENTER_VIEW"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: [], notes: "Official IT role home; only reads telemetry and registry projections." },
  },
{
    id: "system-watchdog",
    label: "Watchdog",
    description: "Unified IT health page that combines module health, watchdog alerts, and external integration status.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 2 },
    routes: [roleRoute("system", "/system/watchdog")],
    apis: [
      api("GET", "/api/modules/health", "bff"),
      api("GET", "/api/bff/system/watchdog-events", "bff"),
      api("GET", "/api/bff/system/integration-overview", "bff"),
    ],
    data: [
      { table: "watchdog_events", entity: "watchdog event stream", source: "telemetry", status: implemented },
      { table: "integration_error_logs", entity: "integration health signals", source: "telemetry", status: planned },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Watchdog events and registry health.", status: partial },
      { provider: "UNKNOWN", purpose: "External watchdogs can post events with internal token.", status: external },
    ],
    bff: { systemSectionKey: "watchdog", plannedEndpoints: ["/api/bff/system/watchdog-events", "/api/bff/system/integration-overview"] },
    telemetry: { trackPageView: true, auditRequired: true, eventTypes: ["MODULE_HEALTH_VIEW", "WATCHDOG_EVENT_VIEW", "INTEGRATION_STATUS_VIEW"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Replaces the old health, alerts, and integrations pages in navigation." },
  },
{
    id: "system-operations",
    label: "運維協助中心",
    description: "IT operations helper for user lookup, soft interventions, cache refresh, and notification resend.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 3 },
    routes: [roleRoute("system", "/system/operations")],
    apis: [
      api("GET", "/api/bff/system/operations/user-search", "bff"),
      api("GET", "/api/bff/system/operations/user/:userId", "bff"),
      api("POST", "/api/bff/system/operations/user/:userId/reset-session", "bff"),
      api("POST", "/api/bff/system/operations/user/:userId/refresh-cache", "bff"),
      api("POST", "/api/bff/system/operations/user/:userId/resend-notification", "bff"),
      api("GET", "/api/bff/system/operations/recent-assists", "bff"),
    ],
    data: [
      { table: "users", entity: "operation target identity", source: "postgres", status: legacy },
      { table: "sessions_index", entity: "session clear target", source: "postgres", status: partial },
      { table: "audit_logs", entity: "operation intervention audit trail", source: "telemetry", status: implemented },
      { table: "client_errors", entity: "recent user client errors", source: "telemetry", status: implemented },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "User/session lookup and operation audit trail.", status: partial }],
    bff: {
      systemSectionKey: "operations",
      plannedEndpoints: [
        "/api/bff/system/operations/user-search",
        "/api/bff/system/operations/user/:userId",
        "/api/bff/system/operations/user/:userId/reset-session",
        "/api/bff/system/operations/user/:userId/refresh-cache",
        "/api/bff/system/operations/user/:userId/resend-notification",
        "/api/bff/system/operations/recent-assists",
      ],
      uiStates: ["loading", "ready", "empty", "error", "disabled"],
      freshness: "realtime",
      uiStateSourceFiles: ["client/src/modules/system/operations/page.tsx"],
      sharedComponents: ["DenseRow"],
    },
    telemetry: { trackPageView: true, auditRequired: true, eventTypes: ["OPS_RESET_SESSION", "OPS_REFRESH_CACHE", "OPS_RESEND_NOTIFICATION"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Soft interventions require a reason and are audit-logged before execution; system users cannot be targeted." },
  },
{
    id: "system-insights",
    label: "行為洞察",
    description: "Behavior analytics for module usage, completion rates, role trends, facility trends, and time trends.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 4 },
    routes: [roleRoute("system", "/system/insights")],
    apis: [
      api("GET", "/api/bff/system/insights/overview", "bff"),
      api("GET", "/api/bff/system/insights/module/:moduleId", "bff"),
    ],
    data: [
      { table: "ui_events", entity: "module behavior events", source: "telemetry", status: implemented },
      { table: "audit_logs", entity: "completion event audit trail", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Behavioral trend rollups from telemetry tables.", status: partial }],
    bff: { systemSectionKey: "insights", plannedEndpoints: ["/api/bff/system/insights/overview", "/api/bff/system/insights/module/:moduleId"] },
    telemetry: { trackPageView: true, eventTypes: ["INSIGHTS_VIEW", "INSIGHTS_DRILL_DOWN"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Read-only usage analytics from ui_events and selected audit completion events." },
  },
{
    id: "system-governance",
    label: "治理面",
    description: "Governance hub for module registry, function relations, topology notes, and audit raw views.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 5 },
    routes: [roleRoute("system", "/system/governance")],
    apis: [
      api("GET", "/api/modules/registry", "bff"),
      api("GET", "/api/system/module-registry", "bff"),
      api("GET", "/api/audit/logs", "telemetry"),
    ],
    data: [
      { table: "module_settings", entity: "module governance settings", source: "postgres", status: partial },
      { table: "audit_logs", entity: "audit raw records", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Registry settings and audit governance.", status: partial }],
    bff: { systemSectionKey: "governance", plannedEndpoints: ["/api/modules/registry", "/api/audit/logs"] },
    telemetry: { trackPageView: true, auditRequired: true, eventTypes: ["ARCHITECTURE_RELATION_VIEW", "TOPOLOGY_VIEW", "AUDIT_LOG_VIEW"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Replaces old function-relations, topology, audit, and auxiliary observer nav entries." },
    legacy: { oldRoutes: ["/system/function-relations", "/system/topology", "/system/audit", "/system/training-views"], migrationNotes: "These former observer pages are now tabs inside /system/governance." },
  },
{
    id: "linebot-management",
    label: "400LINE 管理",
    description: "System domain entry for monitoring 400LINE / LINE Bot Assistant service health, facility groups, whitelist snapshots, announcement pipeline, and API readiness.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { system: 6 },
    routes: [roleRoute("system", "/system/linebot-management")],
    apis: [
      api("GET", "/api/bff/system/linebot-management/overview", "bff"),
      api("GET", "/api/bff/system/linebot-management/services", "bff"),
      api("GET", "/api/bff/system/linebot-management/facilities", "bff"),
      api("GET", "/api/bff/system/linebot-management/whitelist-snapshot", "bff"),
      api("GET", "/api/bff/system/linebot-management/announcement-pipeline", "bff"),
    ],
    data: [
      { entity: "400LINE service health snapshot", source: "external", status: partial, notes: "Normalized from 400LINE JSON endpoints; waiting endpoints are surfaced without throwing UI errors." },
      { table: "line_feature_whitelist", entity: "400QIAN whitelist shadow snapshot", source: "postgres", status: implemented },
    ],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "Authority for LINE official account services, feature whitelist, facility groups, and announcement pipeline readiness.", status: external },
      { provider: "RAGIC", purpose: "H01 employee source with H02 fallback for name, LINE userId, phone, and department matching.", status: external },
      { provider: "POSTGRES", purpose: "400QIAN shadow comparison for whitelist state.", status: implemented },
    ],
    bff: {
      systemSectionKey: "linebotManagement",
      plannedEndpoints: [
        "/api/bff/system/linebot-management/overview",
        "/api/bff/system/linebot-management/services",
        "/api/bff/system/linebot-management/facilities",
        "/api/bff/system/linebot-management/whitelist-snapshot",
        "/api/bff/system/linebot-management/announcement-pipeline",
      ],
      uiStates: ["loading", "ready", "empty", "error", "degraded", "stale"],
      freshness: "5min",
      uiStateSourceFiles: ["client/src/modules/system/linebot-management/page.tsx"],
      sharedComponents: ["FreshnessIndicator"],
    },
    telemetry: { trackPageView: true, eventTypes: ["LINEBOT_MANAGEMENT_VIEW", "LINEBOT_API_READINESS_VIEW"] },
    governance: {
      ownerRole: "SYSTEM_ADMIN",
      editableBy: ["SYSTEM_ADMIN"],
      readonlyFor: ["system"],
      notes: "400LINE is the source of truth. This shell is read-only and must not expose secret values.",
    },
  },
{
    id: "helper-status",
    label: "400LINE 服務監控",
    description: "Legacy detailed service-status view for 400LINE external services, exposed endpoints, required secrets, and resilience rules.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "private",
    homepageWidget: true,
    priority: { system: 7 },
    routes: [roleRoute("system", "/system/lineXBS-status"), roleRoute("system", "/system/helper-status", legacy)],
    apis: [api("GET", "/api/bff/system/helper-status", "bff")],
    data: [{ entity: "external service catalog", source: "private", status: implemented, notes: "Seeded from the external service list markdown and redacts secret values." }],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "LINE Messaging API and webhook status source.", status: external },
      { provider: "UNKNOWN", purpose: "OpenAI API for AI helper features.", status: external },
      { provider: "UNKNOWN", purpose: "Google Gemini API for announcement classifier Pass 2.", status: external },
      { provider: "RAGIC", purpose: "Employee and caution-list lookups.", status: external },
      { provider: "UNKNOWN", purpose: "CWA weather and UV data.", status: external },
    ],
    bff: {
      systemSectionKey: "helperStatus",
      plannedEndpoints: ["/api/bff/system/helper-status"],
      uiStates: ["loading", "ready", "empty", "error", "degraded"],
      freshness: "5min",
      uiStateSourceFiles: ["client/src/modules/system/helper-status/page.tsx"],
      sharedComponents: ["DenseRow", "FreshnessIndicator"],
    },
    telemetry: { trackPageView: true, eventTypes: ["HELPER_STATUS_VIEW"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Belongs to the 400LINE domain under /system/linebot-management. Values show configured/missing state only; never expose secret contents." },
  },
{
    id: "line-whitelist",
    label: "400 LINE 白名單管理",
    description: "System-managed whitelist for 400 LINE official account feature access, including interview and caution-query feature switches.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { system: 8 },
    routes: [roleRoute("system", "/system/line-whitelist")],
    apis: [
      api("GET", "/api/bff/system/line-whitelist", "bff"),
      api("GET", "/api/bff/system/line-whitelist/candidates", "bff"),
      api("POST", "/api/bff/system/line-whitelist", "crud"),
      api("PATCH", "/api/bff/system/line-whitelist/:id", "crud"),
      api("GET", "/api/internal/line-whitelist/check", "bff", partial),
      api("GET", "/api/cms/system/caution-permissions", "bff"),
      api("GET", "/api/cms/system/caution-permissions/candidates", "bff"),
      api("POST", "/api/cms/system/caution-permissions", "crud"),
      api("PATCH", "/api/cms/system/caution-permissions/:id/period", "crud"),
      api("PATCH", "/api/cms/system/caution-permissions/:id/status", "crud"),
      api("GET", "/api/cms/system/caution-permissions/check", "bff"),
      api("GET", "/api/cms/system/caution-permissions/:id/audit", "telemetry"),
      api("POST", "/api/cms/system/caution-permissions/:id/log-usage", "telemetry"),
    ],
    data: [
      { table: "line_feature_whitelist", entity: "LINE official account feature whitelist", source: "postgres", status: implemented },
      { table: "caution_query_permissions", entity: "caution query permission", source: "postgres", status: implemented },
      { table: "caution_query_permission_audit", entity: "caution query permission audit trail", source: "postgres", status: implemented },
    ],
    integrations: [
      { provider: "RAGIC", purpose: "Employee candidate source for name, userid, phone, and department.", status: external },
      { provider: "LINE_BOT_ASSISTANT", purpose: "External LINE webhook checks feature access by lineUserId.", status: external },
      { provider: "POSTGRES", purpose: "Whitelist status, feature switches, and authorization window.", status: implemented },
    ],
    bff: {
      systemSectionKey: "lineWhitelist",
      plannedEndpoints: [
        "/api/bff/system/line-whitelist",
        "/api/bff/system/line-whitelist/candidates",
        "/api/internal/line-whitelist/check",
        "/api/cms/system/caution-permissions",
        "/api/cms/system/caution-permissions/candidates",
        "/api/cms/system/caution-permissions/check",
      ],
    },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["LINE_WHITELIST_CREATED", "LINE_WHITELIST_UPDATED"] },
    governance: {
      ownerRole: "SYSTEM_ADMIN",
      editableBy: ["SYSTEM_ADMIN"],
      readonlyFor: ["system"],
      notes: "Entries are never deleted through the CMS; disable status or expiry must be used to revoke access.",
    },
  },
];
