import type { ModuleDefinition } from "../types";
import { adminRoute, api, deprecated, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const governanceModules: ModuleDefinition[] = [
{
    id: "legacy-users",
    label: "Legacy Users",
    description: "Original users table and username/password compatibility layer.",
    domainType: "legacy",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/auth/login", "auth", partial)],
    data: [{ table: "users", entity: "legacy user", source: "postgres", status: legacy }],
    integrations: [{ provider: "POSTGRES", purpose: "Legacy user credentials.", status: legacy }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Legacy compatibility only; do not expand this table as the main identity model." },
  },
{
    id: "facilities",
    label: "Facilities",
    description: "Facility records and shared facility key/group mapping.",
    domainType: "core",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["background_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/auth/active-facility", "auth", partial)],
    data: [{ table: "facilities", entity: "facility", source: "postgres", status: partial }],
    integrations: [
      { provider: "RAGIC", purpose: "Facility grants and department mapping.", status: external },
      { provider: "LINE_BOT_ASSISTANT", purpose: "LINE group to facility mapping.", status: external },
    ],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Facility mapping is shared domain truth; route guards must not trust URL alone." },
  },
{
    id: "session-governance",
    label: "Session Governance",
    description: "Session index, role switching, facility switching, and permission snapshots.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/auth/me", "auth"), api("POST", "/api/auth/active-role", "auth"), api("POST", "/api/auth/active-facility", "auth")],
    data: [
      { table: "sessions_index", entity: "session index", source: "postgres", status: partial },
      { table: "user_role_snapshots", entity: "role snapshot", source: "postgres", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Session governance tables.", status: partial }],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true, eventTypes: ["role_switch", "facility_switch"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], requiresApproval: true, notes: "Partial until Redis/opaque session and CSRF hardening are complete." },
  },
{
    id: "user-role-snapshots",
    label: "User Role Snapshots",
    description: "Captured role/facility/permission snapshots from HR or system authority.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/auth/me", "auth", partial)],
    data: [{ table: "user_role_snapshots", entity: "user role snapshot", source: "postgres", status: partial }],
    integrations: [{ provider: "RAGIC", purpose: "Source of employee role/facility state.", status: external }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Snapshots are supporting evidence, not an employee-editable surface." },
  },
{
    id: "employee-resources",
    label: "Employee Resources",
    description: "Employee-owned documents, Notion-like links, events, and sticky notes.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["employee", "lifeguard", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 14 },
    routes: [roleRoute("employee", "/employee/documents", partial), roleRoute("employee", "/employee/more", partial), portalRoute("/portal/:facilityKey/manage", partial)],
    apis: [
      api("GET", "/api/portal/employee-resources", "crud"),
      api("POST", "/api/portal/employee-resources", "crud"),
      api("PATCH", "/api/portal/employee-resources/:id", "crud"),
      api("DELETE", "/api/portal/employee-resources/:id", "crud"),
    ],
    data: [{ table: "employee_resources", entity: "employee resource", source: "postgres", status: implemented, notes: "sub_category and sort_order support document link categorization and user ordering." }],
    integrations: [{ provider: "POSTGRES", purpose: "Employee-created resources.", status: implemented }],
    bff: { employeeSectionKey: "documents", supervisorSectionKey: "settings" },
    telemetry: { trackActionSubmit: true, eventTypes: ["resource_create"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Employees can create scoped resources; supervisors can moderate/edit where allowed." },
  },
{
    id: "employee-training",
    label: "Employee Training",
    description: "Employee training library for work videos, images, notes, and operational learning material.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "lifeguard", "supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: { employee: 15, supervisor: 15, system: 22 },
    routes: [
      roleRoute("employee", "/employee/training", partial),
      roleRoute("supervisor", "/supervisor/training", partial),
      roleRoute("system", "/system/training-views", partial),
    ],
    apis: [
      api("GET", "/api/portal/employee-resources", "crud", partial),
      api("POST", "/api/portal/employee-resources", "crud", partial),
      api("PATCH", "/api/portal/employee-resources/:id", "crud", partial),
      api("DELETE", "/api/portal/employee-resources/:id", "crud", partial),
      api("GET", "/api/bff/employee/home", "bff", partial),
      api("GET", "/api/telemetry/training-views", "telemetry", partial),
    ],
    data: [{ table: "employee_resources", entity: "training resource", source: "postgres", status: implemented, notes: "category=training, url may point to video/image/link material." }],
    integrations: [{ provider: "POSTGRES", purpose: "Employee training resources and material metadata.", status: implemented }],
    bff: { employeeSectionKey: "training" },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["TRAINING_VIEW", "resource_create"] },
    governance: {
      ownerRole: "supervisor",
      editableBy: ["supervisor", "system"],
      readonlyFor: ["employee"],
      notes: "Employee reader, supervisor material management, and system training-view report are wired; still partial until role-specific acceptance coverage is complete.",
    },
  },
{
    id: "widget-layout-settings",
    label: "Widget Layout Settings",
    description: "Deprecated legacy widget layout storage retained for compatibility only.",
    domainType: "support",
    status: deprecated,
    visibleRoles: ["system"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/portal/layout-settings", "legacy", deprecated), api("PATCH", "/api/portal/layout-settings", "legacy", deprecated)],
    data: [{ table: "widget_layout_settings", entity: "widget layout setting", source: "legacy", status: deprecated, notes: "Supervisor settings UI was removed; table/API are retained only for compatibility." }],
    integrations: [{ provider: "POSTGRES", purpose: "Legacy widget layout storage retained for compatibility.", status: deprecated }],
    bff: {},
    telemetry: { trackActionSubmit: true, auditRequired: true, eventTypes: ["layout_update"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Supervisor settings page and widget layout editing are removed from current scope; do not build new flows against this module without a new product decision." },
  },
{
    id: "watchdog-events",
    label: "Watchdog Events",
    description: "External watchdog event ingestion retained as the event source behind system-watchdog.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "system_only", "background_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 5 },
    routes: [roleRoute("system", "/system/alerts", partial)],
    apis: [api("GET", "/api/bff/system/watchdog-events", "bff"), api("POST", "/api/watchdog/events", "telemetry")],
    data: [{ table: "watchdog_events", entity: "watchdog event", source: "telemetry", status: implemented }],
    integrations: [{ provider: "UNKNOWN", purpose: "External watchdogs can post with internal token.", status: external }],
    bff: { systemSectionKey: "watchdogEvents", plannedEndpoints: ["/api/bff/system/watchdog-events"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Write API is token-protected and system-facing." },
  },
{
    id: "bff-projections",
    label: "BFF Projections",
    description: "Projection tables that back employee, supervisor, and system BFF responses.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "projection",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/bff/employee/home", "bff", partial), api("GET", "/api/bff/supervisor/dashboard", "bff", partial), api("GET", "/api/bff/system/overview", "bff", partial)],
    data: [
      { table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial },
      { table: "supervisor_dashboard_projection", entity: "supervisor dashboard projection", source: "projection", status: partial },
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Projection persistence.", status: partial },
      { provider: "LINE_BOT_ASSISTANT", purpose: "Projection source/fallback.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Projection source/fallback.", status: external },
    ],
    bff: { employeeSectionKey: "home", supervisorSectionKey: "dashboard", systemSectionKey: "overview" },
    telemetry: { auditRequired: false },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "BFF projection tables are derived state; source truth stays in source systems or local domain tables." },
  },
{
    id: "integration-sync-jobs",
    label: "Integration Sync Jobs",
    description: "Integration status source retained under system-watchdog integrations.",
    domainType: "integration",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/integrations", partial)],
    apis: [api("GET", "/api/bff/system/integration-overview", "bff", partial)],
    data: [
      { table: "integration_error_logs", entity: "integration error log", source: "telemetry", status: planned },
      { table: "sync_job_runs", entity: "sync job run", source: "telemetry", status: planned },
      { table: "source_snapshots", entity: "source snapshot", source: "external", status: planned },
    ],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "Future sync status source.", status: planned },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Future sync status source.", status: planned },
      { provider: "RAGIC", purpose: "Future sync status source.", status: planned },
    ],
    bff: { systemSectionKey: "integrationOverview", plannedEndpoints: ["/api/bff/system/integration-overview"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Planned registry entry for sync observability; no mutating sync runner is added in this round." },
  },
];
