import type { ModuleDefinition } from "../types";
import { adminRoute, api, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const lifeguardModules: ModuleDefinition[] = [
{
    id: "lifeguard-water-quality",
    label: "水質檢測",
    description: "Lifeguard water-quality GPS photo workflow with system watermark and storage-backed records.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 2 },
    routes: [roleRoute("lifeguard", "/lifeguard/water-quality", partial), roleRoute("lifeguard", "/lifeguard/water-quality-photo", legacy)],
    apis: [api("POST", "/api/bff/lifeguard/water-quality", "bff", partial), api("POST", "/api/bff/lifeguard/photo-upload", "bff", partial)],
    data: [{ table: "lifeguard_water_quality_logs", entity: "water quality GPS photo records", source: "postgres", status: partial }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Water quality photo upload storage.", status: partial }, { provider: "UNKNOWN", purpose: "Nominatim server-side reverse geocoding.", status: external }],
    bff: { plannedEndpoints: ["/api/bff/lifeguard/home", "/api/bff/lifeguard/records"] },
    telemetry: { trackPageView: true, trackCardClick: true, auditRequired: true, eventTypes: ["LIFEGUARD_WATER_QUALITY_CREATED", "LIFEGUARD_PHOTO_UPLOADED"] },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "GPS is required before capture; Nominatim/Object Storage degrade without breaking UI." },
  },
{
    id: "lifeguard-coach-dive",
    label: "教練下水",
    description: "Lifeguard coach dive GPS photo records with coach name hook.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 3 },
    routes: [roleRoute("lifeguard", "/lifeguard/coach-dive", partial), roleRoute("lifeguard", "/lifeguard/coach-water-photo", legacy)],
    apis: [api("POST", "/api/bff/lifeguard/coach-dive", "bff", partial), api("POST", "/api/bff/lifeguard/photo-upload", "bff", partial)],
    data: [{ table: "lifeguard_coach_dive_logs", entity: "coach dive GPS photo records", source: "postgres", status: partial }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Coach dive photo upload storage.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/lifeguard/home"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "Use work-log task categories; no standalone schema in this pass." },
  },
{
    id: "lifeguard-cleanup",
    label: "下班打掃",
    description: "Lifeguard closing cleanup GPS photo records.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 4 },
    routes: [roleRoute("lifeguard", "/lifeguard/cleanup", partial), roleRoute("lifeguard", "/lifeguard/closing-cleanup-photo", legacy)],
    apis: [api("POST", "/api/bff/lifeguard/cleanup", "bff", partial), api("POST", "/api/bff/lifeguard/photo-upload", "bff", partial)],
    data: [{ table: "lifeguard_cleanup_logs", entity: "closing cleanup GPS photo records", source: "postgres", status: partial }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Cleanup photo upload storage.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/lifeguard/home"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "Use work-log task categories; no standalone schema in this pass." },
  },
{
    id: "lifeguard-lane-issues",
    label: "水道事項",
    description: "Lifeguard lane notes frame for lane rental, temporary change, and incident notes.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 5 },
    routes: [roleRoute("lifeguard", "/lifeguard/lane-issues", partial), roleRoute("lifeguard", "/lifeguard/lane-notes", legacy)],
    apis: [api("POST", "/api/bff/lifeguard/lane-issues", "bff", partial)],
    data: [{ table: "lifeguard_handover_notes", entity: "lane notes and handover records", source: "postgres", status: partial }],
    integrations: [{ provider: "POSTGRES", purpose: "Future lane note storage through work-log handover categories.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/lifeguard/home"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["lifeguard", "supervisor", "system"], readonlyFor: [], notes: "水道事項 stays under lifeguard work-log and lane-rentals context." },
  },
{
    id: "lifeguard-lost-and-found",
    label: "失物招領",
    description: "Shared lost-and-found records with separated employee and lifeguard workbench entry points.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard", "employee"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 6 },
    routes: [roleRoute("lifeguard", "/lifeguard/lost-and-found", partial), roleRoute("employee", "/employee/lost-and-found", partial)],
    apis: [
      api("GET", "/api/bff/employee/lost-and-found", "bff", partial),
      api("POST", "/api/bff/employee/lost-and-found", "bff", partial),
      api("PATCH", "/api/bff/employee/lost-and-found/:id", "bff", partial),
      api("GET", "/api/bff/lifeguard/lost-and-found", "bff", partial),
      api("POST", "/api/bff/lifeguard/lost-and-found", "bff", partial),
      api("PATCH", "/api/bff/lifeguard/lost-and-found/:id", "bff", partial),
    ],
    data: [{ table: "lifeguard_lost_and_found", entity: "lost item photo and claim status records", source: "postgres", status: partial }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Lost item photo upload storage.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/employee/lost-and-found", "/api/bff/lifeguard/home", "/api/bff/lifeguard/lost-and-found"] },
    telemetry: { trackPageView: true, trackCardClick: true, auditRequired: true, eventTypes: ["LIFEGUARD_LOST_ITEM_CREATED", "LIFEGUARD_LOST_ITEM_UPDATED", "LIFEGUARD_LOST_ITEM_CLAIMED", "LIFEGUARD_LOST_ITEM_DISPOSED"] },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "lifeguard", "supervisor", "system"], readonlyFor: [], notes: "Employee UI stays under /employee and lifeguard UI stays under /lifeguard; BFF endpoints map both entries to the same facility-scoped lost-and-found table." },
  },
{
    id: "lifeguard-lane-rentals",
    label: "水道租借狀態",
    description: "Read-only lane rental grid for lifeguards.",
    domainType: "support",
    status: partial,
    visibleRoles: ["lifeguard"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { lifeguard: 7 },
    routes: [roleRoute("lifeguard", "/lifeguard/lane-rentals", partial)],
    apis: [api("GET", "/api/bff/lifeguard/lane-rentals", "bff", partial)],
    data: [
      { table: "lane_rentals", entity: "lane rental readonly schedule", source: "postgres", status: partial },
      { table: "lane_rental_layouts", entity: "shared lane layout", source: "postgres", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Lane rental readonly projection.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/lifeguard/lane-rentals"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["lifeguard"], notes: "Lifeguard page must stay readonly." },
  },
{
    id: "system-function-relations",
    label: "當前功能關係",
    description: "Legacy function relationship page retained under the Governance tab.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["detail_page", "system_only"],
    sourceOfTruth: "none",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/function-relations")],
    apis: [],
    data: [
      { table: "shared/schema.ts", entity: "database relationship inventory", source: "private", status: implemented },
      { table: "MODULE_REGISTRY", entity: "module and route relationship inventory", source: "private", status: implemented },
      { table: "workbenchRoutes", entity: "role shell route manifest", source: "private", status: implemented },
    ],
    integrations: [{ provider: "UNKNOWN", purpose: "Static architecture relationship map rendered inside the system workbench.", status: implemented }],
    bff: { systemSectionKey: "functionRelations" },
    telemetry: { trackPageView: true, eventTypes: ["ARCHITECTURE_RELATION_VIEW"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "lifeguard", "supervisor"], notes: "Read-only IT documentation page; keep in sync when schema or canonical routes change." },
  },
];
