import type { ModuleDefinition } from "../types";
import { adminRoute, api, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const operationsModules: ModuleDefinition[] = [
{
    id: "analytics",
    label: "Analytics",
    description: "Legacy admin analytics and supervisor report surface.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/analytics"), roleRoute("supervisor", "/supervisor/reports", partial)],
    apis: [api("GET", "/api/portal/analytics", "telemetry", partial), api("GET", "/api/bff/system/ui-event-overview", "bff", partial)],
    data: [
      { table: "portal_events", entity: "portal interaction events", source: "telemetry", status: implemented },
      { table: "ui_events", entity: "workbench UI events", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Analytics rollups from event tables.", status: partial }],
    bff: { supervisorSectionKey: "reports", systemSectionKey: "uiEventOverview", plannedEndpoints: ["/api/bff/system/ui-event-overview"] },
    telemetry: { trackPageView: true, trackCardClick: true, auditRequired: false },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Analytics reads telemetry/projection state only." },
    legacy: { oldRoutes: ["/analytics"], migrationNotes: "Legacy analytics page is registered for coverage but should not receive new data fan-out." },
  },
{
    id: "operations",
    label: "Operations",
    description: "Legacy cross-facility operations dashboard.",
    domainType: "derived",
    status: legacy,
    visibleRoles: ["system", "supervisor"],
    visibility: ["admin_page"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/operations", legacy)],
    apis: [api("GET", "/api/admin/overview", "proxy", legacy)],
    data: [{ table: "source_snapshots", entity: "external operations payload", source: "external", status: partial }],
    integrations: [{ provider: "SMART_SCHEDULE_MANAGER", purpose: "Legacy operations overview proxy.", status: external }],
    bff: { plannedEndpoints: ["/api/bff/supervisor/dashboard"] },
    telemetry: { trackPageView: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Keep route registered; new operations work should move through supervisor/system BFF." },
    legacy: { oldRoutes: ["/operations", "/api/admin/overview"] },
  },
{
    id: "counter-log",
    label: "Counter Log",
    description: "Canonical counter work-log module for daily templates, assigned tasks, recurring tasks, and supervisor review.",
    domainType: "core",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { supervisor: 10 },
    routes: [
      roleRoute("supervisor", "/supervisor/counter-log/submissions", partial),
      roleRoute("supervisor", "/supervisor/counter-log/daily-templates", partial),
      roleRoute("supervisor", "/supervisor/counter-log/assigned-tasks", partial),
      roleRoute("supervisor", "/supervisor/counter-log/recurring-templates", partial),
      roleRoute("system", "/supervisor/counter-log/submissions", partial),
      adminRoute("/admin/counter-logs/daily-templates", partial),
      adminRoute("/admin/counter-logs/assigned-tasks", partial),
      adminRoute("/admin/counter-logs/recurring-templates", partial),
      adminRoute("/admin/counter-logs/submissions", partial),
    ],
    apis: [
      api("GET", "/api/work-logs/today", "crud", partial),
      api("POST", "/api/work-logs/handover", "crud", partial),
      api("GET", "/api/admin/work-logs/templates", "crud", partial),
      api("GET", "/api/admin/work-logs/submissions", "crud", partial),
    ],
    data: [
      { table: "work_log_templates", entity: "counter log template", source: "postgres", status: implemented, notes: "Uses moduleType=counter instead of a separate counter table." },
      { table: "work_log_entries", entity: "counter log entry", source: "postgres", status: implemented, notes: "Counter work is separated by moduleType." },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Counter daily work-log storage and review trail.", status: implemented }],
    bff: { supervisorSectionKey: "counterLog" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["COUNTER_LOG_CREATED", "COUNTER_LOG_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "櫃台畫面沿用 supervisor/counter 工作面；不新增 counter role." },
    legacy: { oldNames: ["counter-logs"], oldRoutes: ["/admin/counter-logs/*"], migrationNotes: "Canonical module id is counter-log; individual admin pages are child routes." },
  },
{
    id: "lane-rentals",
    label: "Lane Rentals",
    description: "松山水道租借管理 for lane booking, renter details, and operational status.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { supervisor: 11 },
    routes: [
      roleRoute("supervisor", "/supervisor/lane-rentals"),
      roleRoute("system", "/supervisor/lane-rentals"),
      adminRoute("/admin/lane-rentals"),
    ],
    apis: [
      api("GET", "/api/lane-rentals", "crud"),
      api("POST", "/api/lane-rentals", "crud"),
      api("PATCH", "/api/lane-rentals/:id", "crud"),
      api("DELETE", "/api/lane-rentals/:id", "crud"),
    ],
    data: [{ table: "lane_rentals", entity: "lane rental", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Lane rental CRUD and conflict checks.", status: implemented }],
    bff: { supervisorSectionKey: "laneRentals" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["LANE_RENTAL_CREATED", "LANE_RENTAL_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "松山水道事項以此 canonical module id 註冊；頁面只作 route." },
  },
{
    id: "courts",
    label: "Courts",
    description: "場地預約模組 covering 新北高中 and 三重商工 calendars, week/month/search/admin views.",
    domainType: "core",
    status: partial,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { supervisor: 12 },
    routes: [
      roleRoute("employee", "/employee/courts/xinbei", partial),
      roleRoute("employee", "/employee/courts/:school", partial),
      roleRoute("employee", "/employee/courts/:school/week", partial),
      roleRoute("employee", "/employee/courts/:school/month", partial),
      roleRoute("employee", "/employee/courts/:school/search", partial),
      roleRoute("employee", "/employee/courts/:school/admin", partial),
      roleRoute("supervisor", "/supervisor/courts/xinbei", partial),
      roleRoute("supervisor", "/supervisor/courts/:school", partial),
      roleRoute("supervisor", "/supervisor/courts/:school/week", partial),
      roleRoute("supervisor", "/supervisor/courts/:school/month", partial),
      roleRoute("supervisor", "/supervisor/courts/:school/search", partial),
      roleRoute("supervisor", "/supervisor/courts/:school/admin", partial),
      roleRoute("system", "/supervisor/courts/xinbei", partial),
      adminRoute("/courts/xinbei", partial),
      adminRoute("/courts/sanchong", partial),
    ],
    apis: [
      api("GET", "/api/courts/reservations", "crud", partial),
      api("POST", "/api/courts/reservations", "crud", partial),
      api("PATCH", "/api/courts/reservations/:id", "crud", partial),
      api("DELETE", "/api/courts/reservations/:id", "crud", partial),
    ],
    data: [
      { table: "court_reservations", entity: "court reservation", source: "postgres", status: partial },
      { table: "court_google_calendar_syncs", entity: "court calendar sync state", source: "postgres", status: partial },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Reservation records and local sync state.", status: partial },
      { provider: "UNKNOWN", purpose: "Google Calendar sync adapter.", status: external },
    ],
    bff: { supervisorSectionKey: "courts" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["COURT_RESERVATION_CREATED", "COURT_SYNC_RUN"] },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "supervisor", "system"], readonlyFor: [], notes: "Use one canonical courts module; school-specific pages remain child routes." },
    legacy: { oldNames: ["courts-xinbei", "courts-sanchong"], oldRoutes: ["/courts/:school/*"] },
  },
{
    id: "parking",
    label: "Parking Management",
    description: "停車場會員與租約管理總入口 for dashboard KPIs, staff-driven lease creation, signing, payment review, and event days.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { supervisor: 9 },
    routes: [
      roleRoute("supervisor", "/supervisor/parking"),
      roleRoute("system", "/supervisor/parking"),
      adminRoute("/admin/parking/dashboard"),
    ],
    apis: [api("GET", "/api/parking/dashboard", "crud")],
    data: [
      { table: "parking_vehicles", entity: "parking vehicle", source: "postgres", status: implemented },
      { table: "parking_contracts", entity: "parking contract", source: "postgres", status: implemented },
      { table: "parking_payments", entity: "parking payment", source: "postgres", status: implemented },
      { table: "parking_event_days", entity: "parking event day", source: "postgres", status: implemented },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Parking lease, vehicle, payment, event-day and signing data.", status: implemented },
      { provider: "OBJECT_STORAGE", purpose: "Signature image and payment screenshot storage.", status: partial },
      { provider: "GMAIL_SMTP", purpose: "First-phase parking notification delivery.", status: planned },
      { provider: "UNKNOWN", purpose: "Future LINE Messaging API via stored lineUserId.", status: planned },
    ],
    bff: { supervisorSectionKey: "parking" },
    telemetry: { trackPageView: true, trackCardClick: true, auditRequired: true, eventTypes: ["PARKING_DASHBOARD_VIEW"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "第一版只給主管與櫃台內部操作；公開查詢/續約入口延後." },
  },
{
    id: "parking-vehicles",
    label: "Parking Vehicles",
    description: "Parking vehicle and owner records, including monthly/season/year/member/team/staff/special/blacklist states.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/parking/vehicles"), roleRoute("system", "/supervisor/parking/vehicles"), adminRoute("/admin/parking/vehicles")],
    apis: [
      api("GET", "/api/parking/vehicles", "crud"),
      api("POST", "/api/parking/vehicles", "crud"),
      api("PATCH", "/api/parking/vehicles/:id", "crud"),
      api("DELETE", "/api/parking/vehicles/:id", "crud"),
    ],
    data: [{ table: "parking_vehicles", entity: "parking vehicle", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Vehicle, owner, status, and expiry records.", status: implemented }],
    bff: { supervisorSectionKey: "parkingVehicles" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["PARKING_VEHICLE_CREATED", "PARKING_VEHICLE_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "櫃台可建車與查車牌；主管維持管控." },
  },
{
    id: "parking-plans",
    label: "Parking Plans",
    description: "Admin-defined parking plans for term length, pricing, deposit, signing, payment, review and renewal policy.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/parking/plans"), roleRoute("system", "/supervisor/parking/plans"), adminRoute("/admin/parking/plans")],
    apis: [
      api("GET", "/api/parking/plans", "crud"),
      api("POST", "/api/parking/plans", "crud"),
      api("PATCH", "/api/parking/plans/:id", "crud"),
      api("DELETE", "/api/parking/plans/:id", "crud"),
    ],
    data: [{ table: "parking_plans", entity: "parking plan", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Plan pricing and renewal policy.", status: implemented }],
    bff: { supervisorSectionKey: "parkingPlans" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["PARKING_PLAN_CREATED", "PARKING_PLAN_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Plans are supervisor-controlled and can be disabled without deleting history." },
  },
{
    id: "parking-contracts",
    label: "Parking Contracts",
    description: "Parking contracts, staff-issued signing links, electronic signatures, PDF contract generation state, renewal, termination, and refund records.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/parking/contracts"), roleRoute("system", "/supervisor/parking/contracts"), adminRoute("/admin/parking/contracts"), { path: "/parking/sign/:token", kind: "external", status: implemented }],
    apis: [
      api("GET", "/api/parking/contracts", "crud"),
      api("POST", "/api/parking/contracts", "crud"),
      api("PATCH", "/api/parking/contracts/:id", "crud"),
      api("POST", "/api/parking/contracts/:id/sign", "crud"),
      api("POST", "/api/parking/contracts/:id/issue-sign-link", "crud"),
      api("POST", "/api/parking/contracts/:id/terminate", "crud"),
      api("POST", "/api/parking/contracts/:id/refund", "crud"),
      api("GET", "/api/parking/sign-tokens/:token", "crud"),
      api("POST", "/api/parking/sign-tokens/:token/finalize", "crud"),
    ],
    data: [{ table: "parking_contracts", entity: "parking contract", source: "postgres", status: implemented }],
    integrations: [
      { provider: "POSTGRES", purpose: "Contract lifecycle, status, sign token hash and PDF metadata.", status: implemented },
      { provider: "OBJECT_STORAGE", purpose: "Signature image and generated contract artifacts.", status: partial },
    ],
    bff: { supervisorSectionKey: "parkingContracts" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["PARKING_CONTRACT_CREATED", "PARKING_CONTRACT_SIGNED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Signing token is staff-issued; not a standalone public member portal in this phase." },
  },
{
    id: "parking-payments",
    label: "Parking Payments",
    description: "Parking payment reporting and supervisor approval/rejection; approved payments update contract and vehicle effective dates.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/parking/payments"), roleRoute("system", "/supervisor/parking/payments"), adminRoute("/admin/parking/payments")],
    apis: [
      api("GET", "/api/parking/payments", "crud"),
      api("POST", "/api/parking/payments", "crud"),
      api("POST", "/api/parking/payments/:id/review", "crud"),
    ],
    data: [{ table: "parking_payments", entity: "parking payment", source: "postgres", status: implemented }],
    integrations: [
      { provider: "POSTGRES", purpose: "Payment status, transfer last five digits, screenshots, and review result.", status: implemented },
      { provider: "OBJECT_STORAGE", purpose: "Payment screenshot upload storage.", status: partial },
    ],
    bff: { supervisorSectionKey: "parkingPayments" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["PARKING_PAYMENT_REPORTED", "PARKING_PAYMENT_REVIEWED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "付款回報不可自動生效；必須由主管/櫃台後台審核." },
  },
{
    id: "parking-event-days",
    label: "Parking Event Days",
    description: "Parking event-day restrictions and notification content for monthly, member, team, staff and special vehicle categories.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/parking/event-days"), roleRoute("system", "/supervisor/parking/event-days"), adminRoute("/admin/parking/event-days")],
    apis: [
      api("GET", "/api/parking/event-days", "crud"),
      api("POST", "/api/parking/event-days", "crud"),
      api("PATCH", "/api/parking/event-days/:id", "crud"),
      api("DELETE", "/api/parking/event-days/:id", "crud"),
    ],
    data: [{ table: "parking_event_days", entity: "parking event day", source: "postgres", status: implemented }],
    integrations: [
      { provider: "POSTGRES", purpose: "Event-day restriction and announcement content.", status: implemented },
      { provider: "GMAIL_SMTP", purpose: "First-phase event day reminder email.", status: planned },
    ],
    bff: { supervisorSectionKey: "parkingEventDays" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["PARKING_EVENT_DAY_CREATED", "PARKING_EVENT_DAY_UPDATED"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "活動日提醒先走 Email；LINE lineUserId 欄位與 API 串接保留." },
  },
{
    id: "hr-audit",
    label: "HR Audit",
    description: "HR and permission audit placeholder tied to Ragic employee authority and schedule signals.",
    domainType: "support",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["admin_page", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/hr-audit", partial)],
    apis: [api("POST", "/api/hr-audit", "legacy", partial), api("GET", "/api/admin/interview-users", "proxy", legacy)],
    data: [
      { table: "user_role_snapshots", entity: "role grant snapshots", source: "postgres", status: partial },
      { table: "auth_audit_logs", entity: "auth audit log", source: "postgres", status: partial },
    ],
    integrations: [
      { provider: "RAGIC", purpose: "Employee status and HR truth.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Interview users and schedule-side HR signals.", status: external },
    ],
    bff: { systemSectionKey: "audit", plannedEndpoints: ["/api/hr-audit"] },
    telemetry: { auditRequired: true, eventTypes: ["hr_audit"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], requiresApproval: true, notes: "HR audit write behavior is not fully implemented yet." },
    legacy: { oldRoutes: ["/hr-audit", "/api/hr-audit"] },
  },
{
    id: "system-health",
    label: "System Health",
    description: "Legacy system health entry retained as a Watchdog tab source.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "admin_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 2 },
    routes: [adminRoute("/system-health"), roleRoute("system", "/system/health"), roleRoute("system", "/system/integrations")],
    apis: [
      api("GET", "/api/bff/system/health-overview", "bff"),
      api("GET", "/api/bff/system/integration-overview", "bff"),
      api("GET", "/api/bff/system/overview", "bff", partial),
    ],
    data: [
      { table: "integration_error_logs", entity: "integration errors", source: "telemetry", status: partial },
      { table: "sync_job_runs", entity: "sync job runs", source: "telemetry", status: partial },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Health and integration status records.", status: partial },
      { provider: "NEON", purpose: "Production database profile status.", status: partial },
    ],
    bff: { systemSectionKey: "health", plannedEndpoints: ["/api/bff/system/health-overview", "/api/bff/system/integration-overview"] },
    telemetry: { trackPageView: true, auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "System health is admin-owned and read-heavy." },
    legacy: { oldRoutes: ["/system-health"] },
  },
];
