import type { ModuleDefinition } from "../types";
import { adminRoute, api, deprecated, external, implemented, legacy, partial, planned, portalRoute, roleRoute } from "../registry-helpers";

export const portalIntegrationModules: ModuleDefinition[] = [
{
    id: "portal-home",
    label: "Portal Home",
    description: "Legacy facility portal home and employee home data migration boundary.",
    domainType: "legacy",
    status: legacy,
    visibleRoles: ["employee", "lifeguard"],
    visibility: ["homepage_widget", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 13 },
    routes: [portalRoute("/portal"), portalRoute("/portal/:facilityKey")],
    apis: [
      api("GET", "/api/facility-home/:groupId/home", "proxy", legacy),
      api("GET", "/api/bff/employee/home", "bff", partial),
    ],
    data: [{ table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Legacy facility-home payload.", status: legacy }],
    bff: { employeeSectionKey: "home", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["pageview", "widget_click"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee"], notes: "Legacy portal remains registered; new employee home should consume BFF." },
    legacy: { oldRoutes: ["/portal", "/portal/:facilityKey", "/api/facility-home/:groupId/home"] },
  },
{
    id: "portal-manage",
    label: "Portal Manage",
    description: "Legacy portal management surface for quick links, employee resources, and announcements.",
    domainType: "legacy",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["portal_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/manage", partial)],
    apis: [
      api("GET", "/api/portal/layout-settings", "legacy", deprecated),
      api("PATCH", "/api/portal/layout-settings", "legacy", deprecated),
      api("GET", "/api/portal/quick-links", "crud"),
      api("GET", "/api/portal/employee-resources", "crud", partial),
      api("GET", "/api/portal/system-announcements", "crud"),
    ],
    data: [
      { table: "quick_links", entity: "quick links", source: "postgres", status: implemented },
      { table: "employee_resources", entity: "employee resources", source: "postgres", status: implemented },
      { table: "system_announcements", entity: "system announcements", source: "postgres", status: implemented },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Local portal management data.", status: implemented }],
    bff: { supervisorSectionKey: "portalManage" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["layout_update", "resource_create"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Legacy manage route aggregates multiple modules and remains registered as a composite." },
    legacy: { oldRoutes: ["/portal/:facilityKey/manage"] },
  },
{
    id: "portal-review",
    label: "Portal Review",
    description: "Legacy portal review view for announcement candidate approval.",
    domainType: "legacy",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["portal_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/review", partial)],
    apis: [api("GET", "/api/announcement-candidates", "proxy", legacy), api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy), api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy)],
    data: [{ table: "audit_logs", entity: "candidate review audit", source: "postgres", status: planned }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Announcement candidate review proxy.", status: external }],
    bff: { supervisorSectionKey: "announcementReview" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], notes: "Legacy portal review should be replaced by supervisor announcement module over time." },
    legacy: { oldRoutes: ["/portal/:facilityKey/review"] },
  },
{
    id: "portal-analytics",
    label: "Portal Analytics",
    description: "Portal event analytics and facility usage reporting.",
    domainType: "derived",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "portal_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/analytics"), roleRoute("system", "/system/audit", partial)],
    apis: [api("GET", "/api/portal/analytics", "telemetry"), api("POST", "/api/portal/events", "telemetry")],
    data: [{ table: "portal_events", entity: "portal event", source: "telemetry", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Portal analytics event table.", status: implemented }],
    bff: { supervisorSectionKey: "portalAnalytics", systemSectionKey: "portalAnalytics" },
    telemetry: { trackPageView: true, eventTypes: ["pageview", "link_click", "widget_click", "search"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Analytics is derived from event tables and should remain read-only for supervisors." },
    legacy: { oldRoutes: ["/portal/:facilityKey/analytics"] },
  },
{
    id: "system-observability",
    label: "System Observability",
    description: "Legacy observability entry retained as a Watchdog/Governance tab source.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 4 },
    routes: [roleRoute("system", "/system"), roleRoute("system", "/system/integrations"), roleRoute("system", "/system/audit")],
    apis: [
      api("GET", "/api/bff/system/overview", "bff", partial),
      api("GET", "/api/bff/system/integration-overview", "bff"),
      api("GET", "/api/bff/system/ui-event-overview", "bff", partial),
    ],
    data: [
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
      { table: "integration_error_logs", entity: "integration error", source: "telemetry", status: partial },
      { table: "bff_latency_logs", entity: "BFF latency", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Observability persistence and projections.", status: partial }],
    bff: { systemSectionKey: "observability", plannedEndpoints: ["/api/bff/system/overview"] },
    telemetry: { trackPageView: true, auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Partial until latency and integration error write paths are fully wired." },
  },
{
    id: "telemetry-audit",
    label: "Telemetry and Audit",
    description: "Legacy telemetry/audit entry retained under the Governance audit tab.",
    domainType: "system",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only", "admin_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/audit", partial)],
    apis: [
      api("POST", "/api/telemetry/ui-events", "telemetry"),
      api("POST", "/api/telemetry/client-error", "telemetry"),
      api("GET", "/api/bff/system/ui-event-overview", "bff", partial),
      api("POST", "/api/portal/events", "telemetry", legacy),
      api("GET", "/api/portal/analytics", "telemetry", legacy),
    ],
    data: [
      { table: "ui_events", entity: "UI event", source: "telemetry", status: implemented },
      { table: "audit_logs", entity: "audit log", source: "telemetry", status: partial },
      { table: "portal_events", entity: "portal event", source: "telemetry", status: implemented },
      { table: "bff_latency_logs", entity: "BFF latency log", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Telemetry/audit tables.", status: partial }],
    bff: { systemSectionKey: "audit", plannedEndpoints: ["/api/bff/system/ui-event-overview"] },
    telemetry: { trackPageView: true, auditRequired: true, eventTypes: ["CARD_CLICK", "CLIENT_ERROR_REPORTED"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Audit writer exists but high-risk business writes still need full coverage." },
  },
{
    id: "linebot-integration",
    label: "LINE Bot Assistant Integration",
    description: "Proxy and fallback integration for announcement candidates, facility home, and LINE group payloads.",
    domainType: "integration",
    status: external,
    visibleRoles: ["system", "supervisor"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("GET", "/api/announcement-dashboard/summary", "proxy", legacy),
      api("GET", "/api/announcement-candidates", "proxy", legacy),
      api("GET", "/api/announcement-candidates/:id", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy),
      api("GET", "/api/announcement-reports/weekly", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/home", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements/:id", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/today-shift", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/handover", "proxy", legacy),
      api("POST", "/api/facility-home/:groupId/announcements/:id/ack", "proxy", legacy),
      api("GET", "/api/bff/system/line-bot/service-status", "bff"),
      api("GET", "/api/bff/system/line-bot/service-status/snapshots", "bff"),
      api("GET", "/api/bff/system/line-bot/interview-users", "proxy"),
      api("POST", "/api/bff/system/line-bot/interview-users", "proxy"),
      api("PATCH", "/api/bff/system/line-bot/interview-users/:userId", "proxy"),
      api("DELETE", "/api/bff/system/line-bot/interview-users/:userId", "proxy"),
      api("GET", "/api/bff/system/line-bot/vip-whitelist", "proxy"),
      api("POST", "/api/bff/system/line-bot/vip-whitelist", "proxy"),
      api("PATCH", "/api/bff/system/line-bot/vip-whitelist/:id", "proxy"),
      api("DELETE", "/api/bff/system/line-bot/vip-whitelist/:id", "proxy"),
      api("GET", "/api/internal/service-health", "bff", partial),
      api("GET", "/api/internal/service-health/snapshots", "bff", partial),
    ],
    data: [{ table: "source_snapshots", entity: "LINE source snapshot", source: "external", status: planned }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "External LINE Bot Assistant upstream.", status: external }],
    bff: {
      plannedEndpoints: [
        "/api/bff/employee/home",
        "/api/bff/system/line-bot/service-status",
        "/api/bff/system/line-bot/service-status/snapshots",
        "/api/internal/service-health",
      ],
    },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "External integration; route proxy remains legacy until adapter extraction is complete." },
    legacy: { oldRoutes: ["/api/announcement-candidates", "/api/facility-home/:groupId/*"] },
  },
{
    id: "schedule-integration",
    label: "Smart Schedule Integration",
    description: "Smart Schedule Manager adapter, admin overview proxy, and normalized schedule snapshot.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["system", "supervisor", "employee", "lifeguard"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("GET", "/api/admin/overview", "proxy", legacy),
      api("GET", "/api/admin/interview-users", "proxy", legacy),
      api("GET", "/api/bff/system/schedule-snapshot", "bff", partial),
    ],
    data: [
      { table: "source_snapshots", entity: "schedule snapshot", source: "external", status: partial },
      { table: "sync_job_runs", entity: "schedule sync job", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "SMART_SCHEDULE_MANAGER", purpose: "Schedule export, staffing, shift reminder, and assignee matching.", status: external }],
    bff: { employeeSectionKey: "shifts", supervisorSectionKey: "staffing", systemSectionKey: "scheduleSnapshot", plannedEndpoints: ["/api/bff/system/schedule-snapshot"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Schedule truth must stay behind adapter/BFF boundaries." },
  },
{
    id: "ragic-integration",
    label: "Ragic Integration",
    description: "Ragic employee auth and HR source adapter with unified in-memory cache (5-min refresh).",
    domainType: "integration",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("POST", "/api/auth/ragic-login", "auth", legacy),
      api("GET", "/api/bff/system/health-overview", "bff", partial),
    ],
    data: [{ table: "user_role_snapshots", entity: "role snapshot from Ragic", source: "postgres", status: partial }],
    integrations: [{ provider: "RAGIC", purpose: "Employee identity, status, department, role grants — cached every 5 min.", status: partial }],
    bff: { plannedEndpoints: ["/api/bff/system/health-overview"] },
    telemetry: { auditRequired: true, eventTypes: ["ragic_cache_refresh", "ragic_auth_success", "ragic_auth_failure"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "External HR authority; RagicCacheService primes on server start and refreshes every 5 minutes." },
  },
{
    id: "gmail-integration",
    label: "Gmail SMTP Integration",
    description: "SMTP delivery for anomaly notification and test email route.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["system"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/test-email", "legacy", partial)],
    data: [{ table: "notification_recipients", entity: "email recipient", source: "postgres", status: implemented }],
    integrations: [{ provider: "GMAIL_SMTP", purpose: "Send anomaly notifications and verify SMTP configuration.", status: partial }],
    bff: { systemSectionKey: "gmailIntegration" },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: [], notes: "Partial because SMTP depends on env credentials and has only a test route." },
  },
{
    id: "file-upload-export",
    label: "File Upload and Export",
    description: "Local uploads for anomaly images and JSON export files for announcement candidates.",
    domainType: "support",
    status: legacy,
    visibleRoles: ["system", "supervisor"],
    visibility: ["background_only", "admin_page"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("POST", "/api/anomaly-report", "upload", legacy),
      api("GET", "/api/announcement-candidates/export/all", "export", legacy),
      api("GET", "/exports/:filename", "export", legacy),
    ],
    data: [{ entity: "local uploads and exports directories", source: "legacy", status: legacy, notes: "Current storage is local filesystem under uploads/ and exports/." }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Future replacement for local uploads/exports.", status: planned, notes: "No object storage adapter is active for these routes yet." }],
    bff: { systemSectionKey: "fileUploadExport" },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Legacy local filesystem persistence; wrap with StorageAdapter before production deployment." },
  },
];
