export const MODULE_IDS = [
  "auth",
  "dashboard",
  "analytics",
  "operations",
  "hr-audit",
  "system-health",
  "announcements",
  "announcement-review",
  "announcement-summary",
  "system-announcements",
  "tasks",
  "handover",
  "anomalies",
  "notification-recipients",
  "campaigns-events",
  "booking-snapshot",
  "shift-reminder",
  "quick-links",
  "notification-center",
  "knowledge-base-qna",
  "employee-training",
  "personal-note",
  "portal-home",
  "portal-manage",
  "portal-review",
  "portal-analytics",
  "system-observability",
  "telemetry-audit",
  "raw-inspector",
  "linebot-integration",
  "schedule-integration",
  "ragic-integration",
  "gmail-integration",
  "file-upload-export",
  "legacy-users",
  "facilities",
  "session-governance",
  "user-role-snapshots",
  "employee-resources",
  "widget-layout-settings",
  "watchdog-events",
  "bff-projections",
  "integration-sync-jobs",
] as const;

export type ModuleId = typeof MODULE_IDS[number];

export const isModuleId = (value: string): value is ModuleId =>
  (MODULE_IDS as readonly string[]).includes(value);
