import { MODULE_IDS, type ModuleId } from "./ids";
import type {
  AppRole,
  ModuleApiBinding,
  ModuleDefinition,
  ModuleDomainType,
  ModuleImplementationStatus,
  ModuleRouteBinding,
} from "./types";

const implemented = "implemented" as const;
const partial = "partial" as const;
const planned = "planned" as const;
const legacy = "legacy" as const;
const external = "external" as const;
const mock = "mock" as const;

const adminRoute = (path: string, status: ModuleImplementationStatus = implemented): ModuleRouteBinding => ({
  path,
  kind: "legacy_admin",
  role: "system",
  status,
});

const portalRoute = (path: string, status: ModuleImplementationStatus = legacy): ModuleRouteBinding => ({
  path,
  kind: "legacy_portal",
  role: "employee",
  status,
});

const roleRoute = (
  role: Extract<AppRole, "employee" | "supervisor" | "system">,
  path: string,
  status: ModuleImplementationStatus = implemented,
): ModuleRouteBinding => ({
  path,
  role,
  kind: role,
  status,
});

const api = (
  method: ModuleApiBinding["method"],
  path: string,
  kind: ModuleApiBinding["kind"],
  status: ModuleImplementationStatus = implemented,
): ModuleApiBinding => ({ method, path, kind, status });

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: "auth",
    label: "Authentication and Session",
    description: "Workbench login, role/facility switching, legacy Ragic portal login, and session governance.",
    domainType: "core",
    status: partial,
    visibleRoles: ["employee", "supervisor", "system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/login", partial), roleRoute("system", "/login", partial)],
    apis: [
      api("POST", "/api/auth/login", "auth"),
      api("POST", "/api/auth/logout", "auth"),
      api("GET", "/api/auth/me", "auth"),
      api("POST", "/api/auth/active-facility", "auth"),
      api("POST", "/api/auth/active-role", "auth"),
      api("POST", "/api/auth/ragic-login", "auth", legacy),
    ],
    data: [
      { table: "users", entity: "legacy user credential", source: "postgres", status: legacy, notes: "Original user table still exists for compatibility." },
      { table: "sessions_index", entity: "session index", source: "postgres", status: partial, notes: "Session index schema exists; cookie/session hardening is still in progress." },
      { table: "auth_audit_logs", entity: "auth audit log", source: "postgres", status: partial },
    ],
    integrations: [
      { provider: "RAGIC", purpose: "Legacy portal employee-number and phone login verification.", status: external },
      { provider: "LOCAL_STORAGE", purpose: "Former portal auth hint; not a source of truth.", status: legacy, notes: "Do not use localStorage as authority." },
      { provider: "POSTGRES", purpose: "Session, user, and audit tables.", status: partial },
    ],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true, eventTypes: ["login", "logout", "role_switch", "facility_switch"] },
    governance: {
      ownerRole: "SYSTEM_ADMIN",
      editableBy: ["SYSTEM_ADMIN"],
      readonlyFor: ["system"],
      requiresApproval: true,
      notes: "Authentication policy is system-governed; legacy Ragic login remains registered until migration is complete.",
    },
    legacy: { oldRoutes: ["/portal/login", "/api/auth/ragic-login"], migrationNotes: "Keep legacy portal route while workbench session becomes the single authority." },
  },
  {
    id: "dashboard",
    label: "Dashboard",
    description: "Legacy admin dashboard plus supervisor/system/employee workbench home shell orchestration.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "projection",
    homepageWidget: true,
    priority: { employee: 1, supervisor: 1, system: 1 },
    routes: [
      adminRoute("/"),
      roleRoute("employee", "/employee"),
      roleRoute("employee", "/employee/home"),
      roleRoute("supervisor", "/supervisor"),
      roleRoute("supervisor", "/supervisor/home"),
      roleRoute("system", "/system"),
      roleRoute("system", "/system/overview"),
    ],
    apis: [
      api("GET", "/api/bff/employee/home", "bff", partial),
      api("GET", "/api/bff/supervisor/dashboard", "bff", partial),
      api("GET", "/api/bff/system/overview", "bff", partial),
      api("GET", "/api/admin/overview", "proxy", legacy),
    ],
    data: [
      { table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial },
      { table: "supervisor_dashboard_projection", entity: "supervisor dashboard projection", source: "projection", status: partial },
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
    ],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "Announcement and employee home fallback summaries.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Supervisor staffing and shift summaries.", status: external },
      { provider: "POSTGRES", purpose: "Projection cache and local portal data.", status: partial },
    ],
    bff: { employeeSectionKey: "home", supervisorSectionKey: "dashboard", systemSectionKey: "overview", plannedEndpoints: ["/api/bff/employee/home", "/api/bff/supervisor/dashboard", "/api/bff/system/overview"] },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["CARD_CLICK"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Dashboard composition should stay in BFF DTOs, not page-local fetch fan-out." },
    legacy: { oldRoutes: ["/", "/api/admin/overview"], migrationNotes: "Legacy admin dashboard remains available while workbench routes are primary." },
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Legacy admin analytics and supervisor report surface.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/analytics"), roleRoute("supervisor", "/supervisor/reports", partial)],
    apis: [api("GET", "/api/portal/analytics", "telemetry", partial), api("GET", "/api/bff/system/ui-event-overview", "bff", partial)],
    data: [
      { table: "portal_events", entity: "portal interaction events", source: "telemetry", status: implemented },
      { table: "ui_events", entity: "workbench UI events", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Analytics rollups from event tables.", status: partial }],
    bff: { supervisorSectionKey: "reports", systemSectionKey: "uiEventOverview", plannedEndpoints: ["/api/bff/system/ui-event-overview"] },
    telemetry: { trackPageView: true, trackCardClick: true, auditRequired: false },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Analytics reads telemetry/projection state only." },
    legacy: { oldRoutes: ["/analytics"], migrationNotes: "Legacy analytics page is registered for coverage but should not receive new data fan-out." },
  },
  {
    id: "operations",
    label: "Operations",
    description: "Legacy cross-facility operations dashboard.",
    domainType: "derived",
    status: legacy,
    visibleRoles: ["system", "supervisor"],
    visibility: ["admin_page"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/operations", legacy)],
    apis: [api("GET", "/api/admin/overview", "proxy", legacy)],
    data: [{ table: "source_snapshots", entity: "external operations payload", source: "external", status: partial }],
    integrations: [{ provider: "SMART_SCHEDULE_MANAGER", purpose: "Legacy operations overview proxy.", status: external }],
    bff: { plannedEndpoints: ["/api/bff/supervisor/dashboard"] },
    telemetry: { trackPageView: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Keep route registered; new operations work should move through supervisor/system BFF." },
    legacy: { oldRoutes: ["/operations", "/api/admin/overview"] },
  },
  {
    id: "hr-audit",
    label: "HR Audit",
    description: "HR and permission audit placeholder tied to Ragic employee authority and schedule signals.",
    domainType: "support",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["admin_page", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/hr-audit", partial)],
    apis: [api("POST", "/api/hr-audit", "legacy", partial), api("GET", "/api/admin/interview-users", "proxy", legacy)],
    data: [
      { table: "user_role_snapshots", entity: "role grant snapshots", source: "postgres", status: partial },
      { table: "auth_audit_logs", entity: "auth audit log", source: "postgres", status: partial },
    ],
    integrations: [
      { provider: "RAGIC", purpose: "Employee status and HR truth.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Interview users and schedule-side HR signals.", status: external },
    ],
    bff: { systemSectionKey: "audit", plannedEndpoints: ["/api/hr-audit"] },
    telemetry: { auditRequired: true, eventTypes: ["hr_audit"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], requiresApproval: true, notes: "HR audit write behavior is not fully implemented yet." },
    legacy: { oldRoutes: ["/hr-audit", "/api/hr-audit"] },
  },
  {
    id: "system-health",
    label: "System Health",
    description: "System health, adapter status, and integration overview.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "admin_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 2 },
    routes: [adminRoute("/system-health"), roleRoute("system", "/system/health"), roleRoute("system", "/system/integrations")],
    apis: [
      api("GET", "/api/bff/system/health-overview", "bff"),
      api("GET", "/api/bff/system/integration-overview", "bff"),
      api("GET", "/api/bff/system/overview", "bff", partial),
    ],
    data: [
      { table: "integration_error_logs", entity: "integration errors", source: "telemetry", status: partial },
      { table: "sync_job_runs", entity: "sync job runs", source: "telemetry", status: partial },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Health and integration status records.", status: partial },
      { provider: "NEON", purpose: "Production database profile status.", status: partial },
    ],
    bff: { systemSectionKey: "health", plannedEndpoints: ["/api/bff/system/health-overview", "/api/bff/system/integration-overview"] },
    telemetry: { trackPageView: true, auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "System health is admin-owned and read-heavy." },
    legacy: { oldRoutes: ["/system-health"] },
  },
  {
    id: "announcements",
    label: "Announcements",
    description: "Employee-visible announcements from LINE candidate data and locally managed system announcements.",
    domainType: "core",
    status: partial,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 2, supervisor: 4 },
    routes: [
      portalRoute("/portal/:facilityKey/announcements"),
      portalRoute("/portal/:facilityKey/announcements/:id"),
      roleRoute("employee", "/employee/announcements"),
      roleRoute("supervisor", "/supervisor/announcements"),
    ],
    apis: [
      api("GET", "/api/facility-home/:groupId/announcements", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements/:id", "proxy", legacy),
      api("POST", "/api/facility-home/:groupId/announcements/:id/ack", "proxy", legacy),
      api("GET", "/api/announcements/acknowledgements", "crud", partial),
      api("POST", "/api/announcements/:id/ack", "crud", partial),
      api("GET", "/api/portal/system-announcements", "crud", partial),
      api("POST", "/api/portal/system-announcements", "crud", partial),
      api("PATCH", "/api/portal/system-announcements/:id", "crud", partial),
      api("DELETE", "/api/portal/system-announcements/:id", "crud", partial),
    ],
    data: [
      { table: "system_announcements", entity: "system announcement", source: "postgres", status: implemented },
      { table: "announcement_acknowledgements", entity: "employee announcement acknowledgement", source: "postgres", status: partial },
      { table: "portal_events", entity: "announcement read/open events", source: "telemetry", status: partial },
    ],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Facility announcements and acknowledgement proxy.", status: external }],
    bff: { employeeSectionKey: "announcements", supervisorSectionKey: "announcementAcks", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["announcement_open", "pageview"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], requiresApproval: false, notes: "Employee-visible content may come from LINE proxy or local system_announcements." },
    legacy: { oldRoutes: ["/portal/:facilityKey/announcements", "/api/facility-home/:groupId/announcements"] },
  },
  {
    id: "announcement-review",
    label: "Announcement Review",
    description: "Supervisor review queue for LINE Bot announcement candidates.",
    domainType: "support",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/announcements"), portalRoute("/portal/:facilityKey/review", partial), roleRoute("supervisor", "/supervisor/announcements")],
    apis: [
      api("GET", "/api/announcement-candidates", "proxy", legacy),
      api("GET", "/api/announcement-candidates/:id", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy),
    ],
    data: [{ table: "audit_logs", entity: "review audit trail", source: "postgres", status: planned, notes: "Server-side audit write path is still planned." }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Candidate approval/rejection upstream.", status: external }],
    bff: { supervisorSectionKey: "announcementReview", plannedEndpoints: ["/api/announcement-candidates"] },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["announcement_approve", "announcement_reject"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], requiresApproval: true, notes: "Review actions must eventually write audit logs." },
    legacy: { oldRoutes: ["/announcements", "/portal/:facilityKey/review"] },
  },
  {
    id: "announcement-summary",
    label: "Announcement Summary",
    description: "Announcement dashboard summary and weekly report export view.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "admin_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/announcements/summary")],
    apis: [
      api("GET", "/api/announcement-dashboard/summary", "proxy", legacy),
      api("GET", "/api/announcement-reports/weekly", "proxy", legacy),
    ],
    data: [{ table: "source_snapshots", entity: "announcement summary snapshot", source: "external", status: partial }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Summary and weekly report upstream.", status: external }],
    bff: { supervisorSectionKey: "announcementSummary", plannedEndpoints: ["/api/announcement-dashboard/summary"] },
    telemetry: { trackPageView: true },
    governance: { ownerRole: "supervisor", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Summary reads upstream report data; local persistence is not complete." },
    legacy: { oldRoutes: ["/announcements/summary"] },
  },
  {
    id: "system-announcements",
    label: "System Announcements",
    description: "Supervisor-maintained operational notices stored locally for portal and employee home display.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 3, supervisor: 5 },
    routes: [portalRoute("/portal/:facilityKey/manage", partial), roleRoute("supervisor", "/supervisor/settings", partial)],
    apis: [
      api("GET", "/api/portal/system-announcements", "crud"),
      api("POST", "/api/portal/system-announcements", "crud"),
      api("PATCH", "/api/portal/system-announcements/:id", "crud"),
      api("DELETE", "/api/portal/system-announcements/:id", "crud"),
    ],
    data: [{ table: "system_announcements", entity: "system announcement", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Local supervisor-managed notices.", status: implemented }],
    bff: { employeeSectionKey: "announcements", supervisorSectionKey: "settings" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Local system announcements are editable by supervisors for their facility scope." },
  },
  {
    id: "tasks",
    label: "Tasks",
    description: "Employee self-created tasks and supervisor-assigned same-facility tasks backed by the dedicated tasks table.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 4, supervisor: 2 },
    routes: [roleRoute("employee", "/employee/tasks"), roleRoute("supervisor", "/supervisor/tasks")],
    apis: [
      api("GET", "/api/tasks", "crud"),
      api("POST", "/api/tasks", "crud"),
      api("PATCH", "/api/tasks/:id", "crud"),
      api("PATCH", "/api/tasks/:id/status", "crud"),
      api("DELETE", "/api/tasks/:id", "crud"),
    ],
    data: [{ table: "tasks", entity: "employee and supervisor task", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Dedicated task CRUD and completion state.", status: implemented }],
    bff: { employeeSectionKey: "tasks", supervisorSectionKey: "incompleteTasks", plannedEndpoints: ["/api/bff/employee/home", "/api/bff/supervisor/dashboard"] },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["task_create", "task_update", "task_complete", "task_delete"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "employee"], readonlyFor: [], notes: "Employees may edit/delete self-created tasks; supervisors manage same-facility tasks; employees may complete assigned or self-created tasks." },
  },
  {
    id: "handover",
    label: "櫃台交接",
    description: "Legacy handover notes plus operational handover assignment/reporting flow.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 5, supervisor: 3 },
    routes: [portalRoute("/portal/:facilityKey/handover"), roleRoute("employee", "/employee/handover"), roleRoute("supervisor", "/supervisor/handover")],
    apis: [
      api("GET", "/api/portal/handovers", "crud"),
      api("POST", "/api/portal/handovers", "crud"),
      api("DELETE", "/api/portal/handovers/:id", "crud"),
      api("POST", "/api/handover", "crud"),
      api("PATCH", "/api/handover/:id/complete", "crud"),
      api("GET", "/api/bff/employee/handover/summary", "bff"),
      api("GET", "/api/bff/employee/handover/list", "bff"),
      api("GET", "/api/portal/operational-handovers", "crud"),
      api("POST", "/api/portal/operational-handovers", "crud"),
      api("PATCH", "/api/portal/operational-handovers/:id", "crud"),
      api("PATCH", "/api/portal/operational-handovers/:id/report", "crud"),
      api("DELETE", "/api/portal/operational-handovers/:id", "crud"),
      api("GET", "/api/facility-home/:groupId/handover", "proxy", legacy),
    ],
    data: [
      { table: "handover_entries", entity: "legacy handover entry", source: "postgres", status: implemented },
      { table: "operational_handovers", entity: "operational handover", source: "postgres", status: implemented },
      { table: "portal_events", entity: "handover events", source: "telemetry", status: implemented },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Local handover persistence.", status: implemented },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Optional assignee resolution from schedule export.", status: partial },
    ],
    bff: { employeeSectionKey: "handover", supervisorSectionKey: "handoverOverview" },
    telemetry: { trackPageView: true, trackActionSubmit: true, eventTypes: ["handover_create", "handover_report", "handover_claim"] },
    governance: { ownerRole: "supervisor", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Employee can create/report scoped items; supervisor governs operational assignments." },
    legacy: { oldRoutes: ["/portal/:facilityKey/handover", "/api/facility-home/:groupId/handover"] },
  },
  {
    id: "anomalies",
    label: "Anomalies",
    description: "Clock-in anomaly reports, review, resolution, and supervisor/system alert surfaces.",
    domainType: "core",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["homepage_widget", "detail_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { supervisor: 6, system: 3 },
    routes: [adminRoute("/anomaly-reports"), roleRoute("supervisor", "/supervisor/anomalies"), roleRoute("system", "/system/alerts")],
    apis: [
      api("POST", "/api/anomaly-report", "upload"),
      api("GET", "/api/anomaly-reports", "crud"),
      api("GET", "/api/anomaly-reports/:id", "crud"),
      api("PATCH", "/api/anomaly-reports/:id/resolution", "crud"),
      api("PATCH", "/api/anomaly-reports/batch/resolution", "crud"),
      api("DELETE", "/api/anomaly-reports/:id", "crud"),
    ],
    data: [
      { table: "anomaly_reports", entity: "anomaly report", source: "postgres", status: implemented },
      { table: "audit_logs", entity: "anomaly resolution audit", source: "postgres", status: planned, notes: "Resolution audit write path is still planned." },
    ],
    integrations: [
      { provider: "GMAIL_SMTP", purpose: "Notification email for new reports/resolution.", status: partial },
      { provider: "OBJECT_STORAGE", purpose: "Current upload path is local uploads; object storage is future replacement.", status: planned },
    ],
    bff: { supervisorSectionKey: "pendingAnomalies", systemSectionKey: "alerts" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], requiresApproval: true, notes: "Anomaly resolution should fail closed into audit before production hardening." },
  },
  {
    id: "notification-recipients",
    label: "Notification Recipients",
    description: "Email recipient management for anomaly notification flows.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["system", "supervisor"],
    visibility: ["admin_page", "background_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [adminRoute("/anomaly-reports", partial)],
    apis: [
      api("GET", "/api/notification-recipients", "crud"),
      api("POST", "/api/notification-recipients", "crud"),
      api("PATCH", "/api/notification-recipients/:id", "crud"),
      api("DELETE", "/api/notification-recipients/:id", "crud"),
    ],
    data: [{ table: "notification_recipients", entity: "notification recipient", source: "postgres", status: implemented }],
    integrations: [{ provider: "GMAIL_SMTP", purpose: "Recipient list controls Gmail notification delivery.", status: partial }],
    bff: { plannedEndpoints: ["/api/notification-recipients"] },
    telemetry: { trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system", "supervisor"], readonlyFor: [], requiresApproval: false, notes: "Recipient edits affect external email delivery and should be audited later." },
  },
  {
    id: "campaigns-events",
    label: "Campaigns and Events",
    description: "Employee-visible events/campaigns from employee resources and announcement candidate fallback.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 6 },
    routes: [portalRoute("/portal/:facilityKey/campaigns"), roleRoute("employee", "/employee/announcements", partial)],
    apis: [api("GET", "/api/portal/employee-resources", "crud", partial), api("POST", "/api/portal/employee-resources", "crud", partial)],
    data: [{ table: "employee_resources", entity: "event resource", source: "postgres", status: implemented, notes: "category=event" }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Campaign fallback extracted from announcement candidates.", status: external }],
    bff: { employeeSectionKey: "campaigns" },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["resource_create"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Employee-created campaign/event content is allowed but scoped by facility." },
    legacy: { oldRoutes: ["/portal/:facilityKey/campaigns"] },
  },
  {
    id: "booking-snapshot",
    label: "Booking Snapshot",
    description: "Booking and occupancy snapshot module reserved for future booking adapter projection.",
    domainType: "integration",
    status: planned,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "background_only"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 10, supervisor: 10, system: 10 },
    routes: [],
    apis: [],
    data: [{ table: "source_snapshots", entity: "booking source snapshot", source: "external", status: planned }],
    integrations: [{ provider: "UNKNOWN", purpose: "Booking adapter exists as a boundary but real provider is not connected.", status: planned }],
    bff: { employeeSectionKey: "bookingSnapshot", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Planned only; connect through booking adapter before exposing as real data." },
  },
  {
    id: "shift-reminder",
    label: "Shift Reminder",
    description: "Today shift and reminder section from Smart Schedule Manager and facility-home proxy.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 7, supervisor: 7 },
    routes: [portalRoute("/portal/:facilityKey/shift"), roleRoute("employee", "/employee/shift")],
    apis: [
      api("GET", "/api/facility-home/:groupId/today-shift", "proxy", legacy),
      api("GET", "/api/bff/employee/shifts/today", "bff", partial),
      api("GET", "/api/bff/system/schedule-snapshot", "bff", partial),
    ],
    data: [{ table: "source_snapshots", entity: "schedule source snapshot", source: "external", status: partial }],
    integrations: [
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Canonical shift export and schedule snapshot.", status: external },
      { provider: "LINE_BOT_ASSISTANT", purpose: "Legacy facility-home today-shift proxy.", status: legacy },
    ],
    bff: { employeeSectionKey: "shifts", supervisorSectionKey: "shifts", systemSectionKey: "scheduleSnapshot", plannedEndpoints: ["/api/bff/system/schedule-snapshot"] },
    telemetry: { trackPageView: true, trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Schedule data should enter through adapter/projection, not direct frontend calls." },
    legacy: { oldRoutes: ["/portal/:facilityKey/shift", "/api/facility-home/:groupId/today-shift"] },
  },
  {
    id: "quick-links",
    label: "Quick Links",
    description: "Supervisor-managed shortcuts used by portal and employee home.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page", "portal_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 8, supervisor: 8 },
    routes: [portalRoute("/portal/:facilityKey/manage"), roleRoute("supervisor", "/supervisor/settings", partial), roleRoute("employee", "/employee/more", partial)],
    apis: [
      api("GET", "/api/portal/quick-links", "crud"),
      api("POST", "/api/portal/quick-links", "crud"),
      api("PATCH", "/api/portal/quick-links/:id", "crud"),
      api("DELETE", "/api/portal/quick-links/:id", "crud"),
    ],
    data: [{ table: "quick_links", entity: "quick link", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Local shortcut persistence.", status: implemented }],
    bff: { employeeSectionKey: "shortcuts", supervisorSectionKey: "settings" },
    telemetry: { trackPageView: true, trackCardClick: true, trackActionSubmit: true, eventTypes: ["link_click"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Supervisor manages facility-scoped quick links." },
    legacy: { oldRoutes: ["/portal/:facilityKey/manage"] },
  },
  {
    id: "notification-center",
    label: "Notification Center",
    description: "Unified in-app notifications planned after core domain events are stable.",
    domainType: "support",
    status: planned,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["homepage_widget", "background_only"],
    sourceOfTruth: "none",
    homepageWidget: true,
    priority: { employee: 11, supervisor: 11, system: 11 },
    routes: [],
    apis: [],
    data: [],
    integrations: [{ provider: "UNKNOWN", purpose: "Will consume domain events after telemetry/audit contract is stable.", status: planned }],
    bff: { employeeSectionKey: "notifications", supervisorSectionKey: "notifications", systemSectionKey: "notifications" },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Planned module; requires event policy before implementation." },
  },
  {
    id: "knowledge-base-qna",
    label: "Knowledge Base Q&A",
    description: "Employee knowledge and Q&A module reserved for future curated content.",
    domainType: "support",
    status: planned,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "none",
    homepageWidget: true,
    priority: { employee: 12 },
    routes: [],
    apis: [],
    data: [],
    integrations: [{ provider: "UNKNOWN", purpose: "No current KB provider is registered.", status: planned }],
    bff: { employeeSectionKey: "qna" },
    telemetry: { trackCardClick: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Planned only; do not add RAG/vector storage without explicit approval." },
  },
  {
    id: "personal-note",
    label: "Personal Note",
    description: "Employee personal note/sticky note surface backed by employee_resources category where available.",
    domainType: "support",
    status: partial,
    visibleRoles: ["employee"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 9 },
    routes: [roleRoute("employee", "/employee/more", partial)],
    apis: [
      api("GET", "/api/portal/employee-resources", "crud", partial),
      api("POST", "/api/portal/employee-resources", "crud", partial),
      api("PATCH", "/api/portal/employee-resources/:id", "crud", partial),
      api("DELETE", "/api/portal/employee-resources/:id", "crud", partial),
    ],
    data: [{ table: "employee_resources", entity: "sticky note resource", source: "postgres", status: implemented, notes: "category=sticky_note" }],
    integrations: [{ provider: "POSTGRES", purpose: "Employee-owned notes through employee_resources.", status: implemented }],
    bff: { employeeSectionKey: "stickyNotes" },
    telemetry: { trackActionSubmit: true, eventTypes: ["resource_create"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Partial because personal-note is a category, not yet a dedicated module UI." },
  },
  {
    id: "portal-home",
    label: "Portal Home",
    description: "Legacy facility portal home and employee home data migration boundary.",
    domainType: "legacy",
    status: legacy,
    visibleRoles: ["employee"],
    visibility: ["homepage_widget", "portal_page"],
    sourceOfTruth: "external",
    homepageWidget: true,
    priority: { employee: 13 },
    routes: [portalRoute("/portal"), portalRoute("/portal/:facilityKey")],
    apis: [
      api("GET", "/api/facility-home/:groupId/home", "proxy", legacy),
      api("GET", "/api/bff/employee/home", "bff", partial),
    ],
    data: [{ table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Legacy facility-home payload.", status: legacy }],
    bff: { employeeSectionKey: "home", plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { trackPageView: true, trackCardClick: true, eventTypes: ["pageview", "widget_click"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee"], notes: "Legacy portal remains registered; new employee home should consume BFF." },
    legacy: { oldRoutes: ["/portal", "/portal/:facilityKey", "/api/facility-home/:groupId/home"] },
  },
  {
    id: "portal-manage",
    label: "Portal Manage",
    description: "Legacy portal management surface for quick links, layout, employee resources, and announcements.",
    domainType: "legacy",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["portal_page", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/manage", partial)],
    apis: [
      api("GET", "/api/portal/layout-settings", "crud", partial),
      api("PATCH", "/api/portal/layout-settings", "crud", partial),
      api("GET", "/api/portal/quick-links", "crud"),
      api("GET", "/api/portal/employee-resources", "crud", partial),
      api("GET", "/api/portal/system-announcements", "crud"),
    ],
    data: [
      { table: "quick_links", entity: "quick links", source: "postgres", status: implemented },
      { table: "widget_layout_settings", entity: "widget layout", source: "postgres", status: implemented },
      { table: "employee_resources", entity: "employee resources", source: "postgres", status: implemented },
      { table: "system_announcements", entity: "system announcements", source: "postgres", status: implemented },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Local portal management data.", status: implemented }],
    bff: { supervisorSectionKey: "settings" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true, eventTypes: ["layout_update", "resource_create"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Legacy manage route aggregates multiple modules and remains registered as a composite." },
    legacy: { oldRoutes: ["/portal/:facilityKey/manage"] },
  },
  {
    id: "portal-review",
    label: "Portal Review",
    description: "Legacy portal review view for announcement candidate approval.",
    domainType: "legacy",
    status: partial,
    visibleRoles: ["supervisor", "system"],
    visibility: ["portal_page"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/review", partial)],
    apis: [api("GET", "/api/announcement-candidates", "proxy", legacy), api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy), api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy)],
    data: [{ table: "audit_logs", entity: "candidate review audit", source: "postgres", status: planned }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "Announcement candidate review proxy.", status: external }],
    bff: { supervisorSectionKey: "announcementReview" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: [], notes: "Legacy portal review should be replaced by supervisor announcement module over time." },
    legacy: { oldRoutes: ["/portal/:facilityKey/review"] },
  },
  {
    id: "portal-analytics",
    label: "Portal Analytics",
    description: "Portal event analytics and facility usage reporting.",
    domainType: "derived",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["detail_page", "portal_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [portalRoute("/portal/:facilityKey/analytics"), roleRoute("system", "/system/audit", partial)],
    apis: [api("GET", "/api/portal/analytics", "telemetry"), api("POST", "/api/portal/events", "telemetry")],
    data: [{ table: "portal_events", entity: "portal event", source: "telemetry", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Portal analytics event table.", status: implemented }],
    bff: { supervisorSectionKey: "portalAnalytics", systemSectionKey: "portalAnalytics" },
    telemetry: { trackPageView: true, eventTypes: ["pageview", "link_click", "widget_click", "search"] },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Analytics is derived from event tables and should remain read-only for supervisors." },
    legacy: { oldRoutes: ["/portal/:facilityKey/analytics"] },
  },
  {
    id: "system-observability",
    label: "System Observability",
    description: "System overview, integration health, UI event overview, and watchdog status.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "detail_page", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 4 },
    routes: [roleRoute("system", "/system"), roleRoute("system", "/system/integrations"), roleRoute("system", "/system/audit")],
    apis: [
      api("GET", "/api/bff/system/overview", "bff", partial),
      api("GET", "/api/bff/system/integration-overview", "bff"),
      api("GET", "/api/bff/system/ui-event-overview", "bff", partial),
    ],
    data: [
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
      { table: "integration_error_logs", entity: "integration error", source: "telemetry", status: partial },
      { table: "bff_latency_logs", entity: "BFF latency", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Observability persistence and projections.", status: partial }],
    bff: { systemSectionKey: "observability", plannedEndpoints: ["/api/bff/system/overview"] },
    telemetry: { trackPageView: true, auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Partial until latency and integration error write paths are fully wired." },
  },
  {
    id: "telemetry-audit",
    label: "Telemetry and Audit",
    description: "UI events, client error reporting, portal events, audit logs, and event rollups.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only", "admin_page"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/audit", partial)],
    apis: [
      api("POST", "/api/telemetry/ui-events", "telemetry"),
      api("POST", "/api/telemetry/client-error", "telemetry"),
      api("GET", "/api/bff/system/ui-event-overview", "bff", partial),
      api("POST", "/api/portal/events", "telemetry", legacy),
      api("GET", "/api/portal/analytics", "telemetry", legacy),
    ],
    data: [
      { table: "ui_events", entity: "UI event", source: "telemetry", status: implemented },
      { table: "audit_logs", entity: "audit log", source: "telemetry", status: partial },
      { table: "portal_events", entity: "portal event", source: "telemetry", status: implemented },
      { table: "bff_latency_logs", entity: "BFF latency log", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Telemetry/audit tables.", status: partial }],
    bff: { systemSectionKey: "audit", plannedEndpoints: ["/api/bff/system/ui-event-overview"] },
    telemetry: { trackPageView: true, auditRequired: true, eventTypes: ["CARD_CLICK", "CLIENT_ERROR_REPORTED"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Audit writer exists but high-risk business writes still need full coverage." },
  },
  {
    id: "raw-inspector",
    label: "Raw Inspector",
    description: "System-only raw endpoint inspector with whitelist constraints.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["detail_page", "system_only"],
    sourceOfTruth: "private",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/raw-inspector", partial)],
    apis: [],
    data: [{ table: "audit_logs", entity: "raw inspector audit", source: "postgres", status: planned, notes: "Server-side audit is noted as remaining technical debt." }],
    integrations: [{ provider: "UNKNOWN", purpose: "Whitelist endpoint inspection; provider depends on selected endpoint.", status: partial }],
    bff: { systemSectionKey: "rawInspector" },
    telemetry: { trackPageView: true, trackActionSubmit: true, auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], requiresApproval: true, notes: "System-only tool; production access must be audited and restricted." },
  },
  {
    id: "linebot-integration",
    label: "LINE Bot Assistant Integration",
    description: "Proxy and fallback integration for announcement candidates, facility home, and LINE group payloads.",
    domainType: "integration",
    status: external,
    visibleRoles: ["system", "supervisor"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("GET", "/api/announcement-dashboard/summary", "proxy", legacy),
      api("GET", "/api/announcement-candidates", "proxy", legacy),
      api("GET", "/api/announcement-candidates/:id", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/approve", "proxy", legacy),
      api("POST", "/api/announcement-candidates/:id/reject", "proxy", legacy),
      api("GET", "/api/announcement-reports/weekly", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/home", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/announcements/:id", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/today-shift", "proxy", legacy),
      api("GET", "/api/facility-home/:groupId/handover", "proxy", legacy),
      api("POST", "/api/facility-home/:groupId/announcements/:id/ack", "proxy", legacy),
    ],
    data: [{ table: "source_snapshots", entity: "LINE source snapshot", source: "external", status: planned }],
    integrations: [{ provider: "LINE_BOT_ASSISTANT", purpose: "External LINE Bot Assistant upstream.", status: external }],
    bff: { plannedEndpoints: ["/api/bff/employee/home"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "External integration; route proxy remains legacy until adapter extraction is complete." },
    legacy: { oldRoutes: ["/api/announcement-candidates", "/api/facility-home/:groupId/*"] },
  },
  {
    id: "schedule-integration",
    label: "Smart Schedule Integration",
    description: "Smart Schedule Manager adapter, admin overview proxy, and normalized schedule snapshot.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["system", "supervisor", "employee"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("GET", "/api/admin/overview", "proxy", legacy),
      api("GET", "/api/admin/interview-users", "proxy", legacy),
      api("GET", "/api/bff/system/schedule-snapshot", "bff", partial),
    ],
    data: [
      { table: "source_snapshots", entity: "schedule snapshot", source: "external", status: partial },
      { table: "sync_job_runs", entity: "schedule sync job", source: "telemetry", status: planned },
    ],
    integrations: [{ provider: "SMART_SCHEDULE_MANAGER", purpose: "Schedule export, staffing, shift reminder, and assignee matching.", status: external }],
    bff: { employeeSectionKey: "shifts", supervisorSectionKey: "staffing", systemSectionKey: "scheduleSnapshot", plannedEndpoints: ["/api/bff/system/schedule-snapshot"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Schedule truth must stay behind adapter/BFF boundaries." },
  },
  {
    id: "ragic-integration",
    label: "Ragic Integration",
    description: "Ragic employee auth and HR source adapter.",
    domainType: "integration",
    status: external,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/auth/ragic-login", "auth", legacy)],
    data: [{ table: "user_role_snapshots", entity: "role snapshot from Ragic", source: "postgres", status: partial }],
    integrations: [{ provider: "RAGIC", purpose: "Employee identity, status, department, role grants.", status: external }],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "External HR authority; local cache must not become stale permission truth." },
  },
  {
    id: "gmail-integration",
    label: "Gmail SMTP Integration",
    description: "SMTP delivery for anomaly notification and test email route.",
    domainType: "integration",
    status: partial,
    visibleRoles: ["system"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "external",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/test-email", "legacy", partial)],
    data: [{ table: "notification_recipients", entity: "email recipient", source: "postgres", status: implemented }],
    integrations: [{ provider: "GMAIL_SMTP", purpose: "Send anomaly notifications and verify SMTP configuration.", status: partial }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: [], notes: "Partial because SMTP depends on env credentials and has only a test route." },
  },
  {
    id: "file-upload-export",
    label: "File Upload and Export",
    description: "Local uploads for anomaly images and JSON export files for announcement candidates.",
    domainType: "support",
    status: legacy,
    visibleRoles: ["system", "supervisor"],
    visibility: ["background_only", "admin_page"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [
      api("POST", "/api/anomaly-report", "upload", legacy),
      api("GET", "/api/announcement-candidates/export/all", "export", legacy),
      api("GET", "/exports/:filename", "export", legacy),
    ],
    data: [{ entity: "local uploads and exports directories", source: "legacy", status: legacy, notes: "Current storage is local filesystem under uploads/ and exports/." }],
    integrations: [{ provider: "OBJECT_STORAGE", purpose: "Future replacement for local uploads/exports.", status: planned, notes: "No object storage adapter is active for these routes yet." }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["supervisor"], notes: "Legacy local filesystem persistence; wrap with StorageAdapter before production deployment." },
  },
  {
    id: "legacy-users",
    label: "Legacy Users",
    description: "Original users table and username/password compatibility layer.",
    domainType: "legacy",
    status: legacy,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "legacy",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/auth/login", "auth", partial)],
    data: [{ table: "users", entity: "legacy user", source: "postgres", status: legacy }],
    integrations: [{ provider: "POSTGRES", purpose: "Legacy user credentials.", status: legacy }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Legacy compatibility only; do not expand this table as the main identity model." },
  },
  {
    id: "facilities",
    label: "Facilities",
    description: "Facility records and shared facility key/group mapping.",
    domainType: "core",
    status: partial,
    visibleRoles: ["employee", "supervisor", "system"],
    visibility: ["background_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("POST", "/api/auth/active-facility", "auth", partial)],
    data: [{ table: "facilities", entity: "facility", source: "postgres", status: partial }],
    integrations: [
      { provider: "RAGIC", purpose: "Facility grants and department mapping.", status: external },
      { provider: "LINE_BOT_ASSISTANT", purpose: "LINE group to facility mapping.", status: external },
    ],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "Facility mapping is shared domain truth; route guards must not trust URL alone." },
  },
  {
    id: "session-governance",
    label: "Session Governance",
    description: "Session index, role switching, facility switching, and permission snapshots.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/auth/me", "auth"), api("POST", "/api/auth/active-role", "auth"), api("POST", "/api/auth/active-facility", "auth")],
    data: [
      { table: "sessions_index", entity: "session index", source: "postgres", status: partial },
      { table: "user_role_snapshots", entity: "role snapshot", source: "postgres", status: partial },
    ],
    integrations: [{ provider: "POSTGRES", purpose: "Session governance tables.", status: partial }],
    bff: { plannedEndpoints: ["/api/auth/me"] },
    telemetry: { auditRequired: true, eventTypes: ["role_switch", "facility_switch"] },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], requiresApproval: true, notes: "Partial until Redis/opaque session and CSRF hardening are complete." },
  },
  {
    id: "user-role-snapshots",
    label: "User Role Snapshots",
    description: "Captured role/facility/permission snapshots from HR or system authority.",
    domainType: "system",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/auth/me", "auth", partial)],
    data: [{ table: "user_role_snapshots", entity: "user role snapshot", source: "postgres", status: partial }],
    integrations: [{ provider: "RAGIC", purpose: "Source of employee role/facility state.", status: external }],
    bff: {},
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Snapshots are supporting evidence, not an employee-editable surface." },
  },
  {
    id: "employee-resources",
    label: "Employee Resources",
    description: "Employee-owned documents, events, and sticky notes.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["employee", "supervisor"],
    visibility: ["homepage_widget", "detail_page"],
    sourceOfTruth: "postgres",
    homepageWidget: true,
    priority: { employee: 14 },
    routes: [roleRoute("employee", "/employee/more", partial), portalRoute("/portal/:facilityKey/manage", partial)],
    apis: [
      api("GET", "/api/portal/employee-resources", "crud"),
      api("POST", "/api/portal/employee-resources", "crud"),
      api("PATCH", "/api/portal/employee-resources/:id", "crud"),
      api("DELETE", "/api/portal/employee-resources/:id", "crud"),
    ],
    data: [{ table: "employee_resources", entity: "employee resource", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Employee-created resources.", status: implemented }],
    bff: { employeeSectionKey: "documents", supervisorSectionKey: "settings" },
    telemetry: { trackActionSubmit: true, eventTypes: ["resource_create"] },
    governance: { ownerRole: "employee", editableBy: ["employee", "supervisor"], readonlyFor: [], notes: "Employees can create scoped resources; supervisors can moderate/edit where allowed." },
  },
  {
    id: "widget-layout-settings",
    label: "Widget Layout Settings",
    description: "Supervisor-controlled widget layout for role home surfaces.",
    domainType: "support",
    status: implemented,
    visibleRoles: ["supervisor", "system"],
    visibility: ["background_only", "admin_page"],
    sourceOfTruth: "postgres",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("supervisor", "/supervisor/settings", partial)],
    apis: [api("GET", "/api/portal/layout-settings", "crud"), api("PATCH", "/api/portal/layout-settings", "crud")],
    data: [{ table: "widget_layout_settings", entity: "widget layout setting", source: "postgres", status: implemented }],
    integrations: [{ provider: "POSTGRES", purpose: "Widget layout storage.", status: implemented }],
    bff: { employeeSectionKey: "layout" },
    telemetry: { trackActionSubmit: true, auditRequired: true, eventTypes: ["layout_update"] },
    governance: { ownerRole: "supervisor", editableBy: ["supervisor", "system"], readonlyFor: ["employee"], notes: "Layout settings are supervisor/system governed, not employee authority." },
  },
  {
    id: "watchdog-events",
    label: "Watchdog Events",
    description: "External watchdog event ingestion and system event listing.",
    domainType: "system",
    status: implemented,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["homepage_widget", "system_only", "background_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: true,
    priority: { system: 5 },
    routes: [roleRoute("system", "/system/alerts", partial)],
    apis: [api("GET", "/api/bff/system/watchdog-events", "bff"), api("POST", "/api/watchdog/events", "telemetry")],
    data: [{ table: "watchdog_events", entity: "watchdog event", source: "telemetry", status: implemented }],
    integrations: [{ provider: "UNKNOWN", purpose: "External watchdogs can post with internal token.", status: external }],
    bff: { systemSectionKey: "watchdogEvents", plannedEndpoints: ["/api/bff/system/watchdog-events"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Write API is token-protected and system-facing." },
  },
  {
    id: "bff-projections",
    label: "BFF Projections",
    description: "Projection tables that back employee, supervisor, and system BFF responses.",
    domainType: "derived",
    status: partial,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "projection",
    homepageWidget: false,
    priority: {},
    routes: [],
    apis: [api("GET", "/api/bff/employee/home", "bff", partial), api("GET", "/api/bff/supervisor/dashboard", "bff", partial), api("GET", "/api/bff/system/overview", "bff", partial)],
    data: [
      { table: "employee_home_projection", entity: "employee home projection", source: "projection", status: partial },
      { table: "supervisor_dashboard_projection", entity: "supervisor dashboard projection", source: "projection", status: partial },
      { table: "system_overview_projection", entity: "system overview projection", source: "projection", status: partial },
    ],
    integrations: [
      { provider: "POSTGRES", purpose: "Projection persistence.", status: partial },
      { provider: "LINE_BOT_ASSISTANT", purpose: "Projection source/fallback.", status: external },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Projection source/fallback.", status: external },
    ],
    bff: { employeeSectionKey: "home", supervisorSectionKey: "dashboard", systemSectionKey: "overview" },
    telemetry: { auditRequired: false },
    governance: { ownerRole: "system", editableBy: ["system"], readonlyFor: ["employee", "supervisor"], notes: "BFF projection tables are derived state; source truth stays in source systems or local domain tables." },
  },
  {
    id: "integration-sync-jobs",
    label: "Integration Sync Jobs",
    description: "Integration error logs, sync job run history, and source snapshots.",
    domainType: "integration",
    status: planned,
    visibleRoles: ["system", "SYSTEM_ADMIN"],
    visibility: ["background_only", "system_only"],
    sourceOfTruth: "telemetry",
    homepageWidget: false,
    priority: {},
    routes: [roleRoute("system", "/system/integrations", partial)],
    apis: [api("GET", "/api/bff/system/integration-overview", "bff", partial)],
    data: [
      { table: "integration_error_logs", entity: "integration error log", source: "telemetry", status: planned },
      { table: "sync_job_runs", entity: "sync job run", source: "telemetry", status: planned },
      { table: "source_snapshots", entity: "source snapshot", source: "external", status: planned },
    ],
    integrations: [
      { provider: "LINE_BOT_ASSISTANT", purpose: "Future sync status source.", status: planned },
      { provider: "SMART_SCHEDULE_MANAGER", purpose: "Future sync status source.", status: planned },
      { provider: "RAGIC", purpose: "Future sync status source.", status: planned },
    ],
    bff: { systemSectionKey: "integrationOverview", plannedEndpoints: ["/api/bff/system/integration-overview"] },
    telemetry: { auditRequired: true },
    governance: { ownerRole: "SYSTEM_ADMIN", editableBy: ["SYSTEM_ADMIN"], readonlyFor: ["system"], notes: "Planned registry entry for sync observability; no mutating sync runner is added in this round." },
  },
];

const statuses: ModuleImplementationStatus[] = [implemented, partial, mock, external, planned, legacy, "deprecated"];
const roles: AppRole[] = ["employee", "supervisor", "system", "SYSTEM_ADMIN"];
const methods: ModuleApiBinding["method"][] = ["GET", "POST", "PATCH", "PUT", "DELETE"];
const apiKinds: ModuleApiBinding["kind"][] = ["bff", "crud", "proxy", "auth", "telemetry", "export", "upload", "legacy"];
const domains: ModuleDomainType[] = ["core", "derived", "support", "system", "integration", "legacy"];

const assert = (condition: boolean, message: string) => {
  if (!condition) throw new Error(message);
};

const priorityKeyForRole = (role: AppRole): keyof ModuleDefinition["priority"] =>
  role === "SYSTEM_ADMIN" ? "system" : role;

export const getModuleById = (id: ModuleId): ModuleDefinition | undefined =>
  MODULE_REGISTRY.find((module) => module.id === id);

export const getModulesByRole = (role: AppRole): ModuleDefinition[] =>
  MODULE_REGISTRY.filter((module) => module.visibleRoles.includes(role));

export const getHomepageModules = (role: AppRole): ModuleDefinition[] =>
  getModulesByRole(role)
    .filter((module) => module.homepageWidget)
    .sort((a, b) => {
      const key = priorityKeyForRole(role);
      return (a.priority[key] ?? Number.MAX_SAFE_INTEGER) - (b.priority[key] ?? Number.MAX_SAFE_INTEGER);
    });

export const getModulesByDomain = (domainType: ModuleDomainType): ModuleDefinition[] =>
  MODULE_REGISTRY.filter((module) => module.domainType === domainType);

export const getImplementedModules = (): ModuleDefinition[] =>
  MODULE_REGISTRY.filter((module) => module.status === "implemented");

export const getPlannedModules = (): ModuleDefinition[] =>
  MODULE_REGISTRY.filter((module) => module.status === "planned");

export const getLegacyModules = (): ModuleDefinition[] =>
  MODULE_REGISTRY.filter((module) => module.status === "legacy" || module.routes.some((route) => route.kind === "legacy_admin" || route.kind === "legacy_portal"));

export const getModuleRoutes = (id: ModuleId): ModuleRouteBinding[] =>
  getModuleById(id)?.routes ?? [];

export const getModuleApis = (id: ModuleId): ModuleApiBinding[] =>
  getModuleById(id)?.apis ?? [];

export const assertModuleRegistryValid = (): void => {
  const ids = new Set<string>();
  const validIds = new Set<string>(MODULE_IDS);

  for (const module of MODULE_REGISTRY) {
    assert(Boolean(module.id), "Module id cannot be empty");
    assert(validIds.has(module.id), `Module id is not declared in MODULE_IDS: ${module.id}`);
    assert(!ids.has(module.id), `Duplicate module id: ${module.id}`);
    ids.add(module.id);

    assert(module.label.trim().length > 0, `Module ${module.id} label cannot be empty`);
    assert(module.description.trim().length > 0, `Module ${module.id} description cannot be empty`);
    assert(statuses.includes(module.status), `Module ${module.id} has invalid status: ${module.status}`);
    assert(domains.includes(module.domainType), `Module ${module.id} has invalid domain type: ${module.domainType}`);
    assert(module.visibleRoles.length > 0, `Module ${module.id} visibleRoles cannot be empty`);

    for (const role of module.visibleRoles) {
      assert(roles.includes(role), `Module ${module.id} has unknown role: ${role}`);
    }

    if (module.homepageWidget) {
      assert(
        module.priority.employee !== undefined || module.priority.supervisor !== undefined || module.priority.system !== undefined,
        `Module ${module.id} homepageWidget=true requires at least one priority`,
      );
    }

    if (module.status === "planned") {
      assert(Boolean(module.governance.notes?.trim()), `Planned module ${module.id} must include governance notes`);
    }

    for (const route of module.routes) {
      assert(Boolean(route.path.trim()), `Module ${module.id} has a route with empty path`);
      assert(statuses.includes(route.status), `Module ${module.id} route ${route.path} has invalid status`);
      if (route.role) assert(roles.includes(route.role), `Module ${module.id} route ${route.path} has unknown role`);
    }

    for (const binding of module.apis) {
      assert(methods.includes(binding.method), `Module ${module.id} API ${binding.path} has invalid method`);
      assert(Boolean(binding.path.trim()), `Module ${module.id} API path cannot be empty`);
      assert(apiKinds.includes(binding.kind), `Module ${module.id} API ${binding.path} has invalid kind`);
      assert(statuses.includes(binding.status), `Module ${module.id} API ${binding.path} has invalid status`);
    }
  }
};
