export const designTokens = {
  color: {
    primary: {
      navy: "#0F1B3D",
      navySoft: "#1E2D5C",
    },
    accent: {
      teal: "#2DD4BF",
      lime: "#A3E635",
    },
    state: {
      mustRead: "#F59E0B",
      important: "#F59E0B",
      reminder: "#3B82F6",
      priority: "#F43F5E",
      normal: "#64748B",
      success: "#10B981",
      muted: "#64748B",
    },
    surface: {
      base: "#F3F6FB",
      elevated: "rgba(255, 255, 255, 0.86)",
      solid: "#FFFFFF",
      soft: "#F7FAFC",
    },
    border: {
      subtle: "#EDF1F6",
      default: "#DFE7EF",
      emphasis: "#C8D8E9",
    },
    text: {
      strong: "#10233F",
      body: "#536175",
      muted: "#8B9AAE",
      inverse: "#FFFFFF",
    },
  },
  typography: {
    fontSize: {
      display: ["2.5rem", { lineHeight: "1.05", fontWeight: "700" }],
      h1: ["1.875rem", { lineHeight: "1.15", fontWeight: "700" }],
      h2: ["1.25rem", { lineHeight: "1.25", fontWeight: "700" }],
      h3: ["1rem", { lineHeight: "1.3", fontWeight: "700" }],
      body: ["0.9375rem", { lineHeight: "1.6", fontWeight: "500" }],
      bodySm: ["0.8125rem", { lineHeight: "1.5", fontWeight: "500" }],
      caption: ["0.75rem", { lineHeight: "1.35", fontWeight: "700" }],
      micro: ["0.6875rem", { lineHeight: "1.25", fontWeight: "700" }],
    },
    fontWeight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    letterSpacing: {
      normal: "0",
      label: "0.12em",
    },
  },
  radius: {
    sm: "6px",
    md: "10px",
    lg: "16px",
    pill: "999px",
  },
  shadow: {
    cardRest: "0 1px 0 rgba(255,255,255,0.8) inset, 0 22px 44px -34px rgba(16,35,63,0.32), 0 1px 2px rgba(16,35,63,0.04)",
    cardHover: "0 1px 0 rgba(255,255,255,0.9) inset, 0 26px 52px -32px rgba(16,35,63,0.36), 0 2px 8px rgba(16,35,63,0.05)",
    cardEmphasis: "0 24px 72px -44px rgba(15,34,58,0.72)",
  },
  spacing: {
    "0": "0",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
  },
} as const;

export const designSystemCssVars = {
  "--ds-primary-navy": designTokens.color.primary.navy,
  "--ds-primary-navy-soft": designTokens.color.primary.navySoft,
  "--ds-accent-teal": designTokens.color.accent.teal,
  "--ds-accent-lime": designTokens.color.accent.lime,
  "--ds-state-must-read": designTokens.color.state.mustRead,
  "--ds-state-important": designTokens.color.state.important,
  "--ds-state-reminder": designTokens.color.state.reminder,
  "--ds-state-priority": designTokens.color.state.priority,
  "--ds-state-normal": designTokens.color.state.normal,
  "--ds-state-success": designTokens.color.state.success,
  "--ds-state-muted": designTokens.color.state.muted,
  "--ds-surface-base": designTokens.color.surface.base,
  "--ds-surface-elevated": designTokens.color.surface.elevated,
  "--ds-surface-solid": designTokens.color.surface.solid,
  "--ds-surface-soft": designTokens.color.surface.soft,
  "--ds-border-subtle": designTokens.color.border.subtle,
  "--ds-border-default": designTokens.color.border.default,
  "--ds-border-emphasis": designTokens.color.border.emphasis,
  "--ds-text-strong": designTokens.color.text.strong,
  "--ds-text-body": designTokens.color.text.body,
  "--ds-text-muted": designTokens.color.text.muted,
  "--ds-text-inverse": designTokens.color.text.inverse,
  "--ds-radius-sm": designTokens.radius.sm,
  "--ds-radius-md": designTokens.radius.md,
  "--ds-radius-lg": designTokens.radius.lg,
  "--ds-radius-pill": designTokens.radius.pill,
  "--ds-shadow-card-rest": designTokens.shadow.cardRest,
  "--ds-shadow-card-hover": designTokens.shadow.cardHover,
  "--ds-shadow-card-emphasis": designTokens.shadow.cardEmphasis,
} as const;

export const tailwindDesignSystem = {
  colors: {
    "primary-navy": designTokens.color.primary.navy,
    "primary-navy-soft": designTokens.color.primary.navySoft,
    "accent-teal": designTokens.color.accent.teal,
    "accent-lime": designTokens.color.accent.lime,
    surface: {
      base: designTokens.color.surface.base,
      elevated: designTokens.color.surface.elevated,
      solid: designTokens.color.surface.solid,
      soft: designTokens.color.surface.soft,
    },
    state: {
      "must-read": designTokens.color.state.mustRead,
      important: designTokens.color.state.important,
      reminder: designTokens.color.state.reminder,
      priority: designTokens.color.state.priority,
      normal: designTokens.color.state.normal,
      success: designTokens.color.state.success,
      muted: designTokens.color.state.muted,
    },
    "border-subtle": designTokens.color.border.subtle,
    "border-default": designTokens.color.border.default,
    "border-emphasis": designTokens.color.border.emphasis,
    "text-strong": designTokens.color.text.strong,
    "text-body": designTokens.color.text.body,
    "text-muted": designTokens.color.text.muted,
    "text-inverse": designTokens.color.text.inverse,
  },
  borderRadius: {
    "ds-sm": "var(--ds-radius-sm)",
    "ds-md": "var(--ds-radius-md)",
    "ds-lg": "var(--ds-radius-lg)",
    "ds-pill": "var(--ds-radius-pill)",
  },
  boxShadow: {
    "card-rest": "var(--ds-shadow-card-rest)",
    "card-hover": "var(--ds-shadow-card-hover)",
    "card-emphasis": "var(--ds-shadow-card-emphasis)",
  },
  spacing: designTokens.spacing,
  fontSize: designTokens.typography.fontSize,
  fontWeight: designTokens.typography.fontWeight,
} as const;
